import type { MetadataRoute } from 'next';
import { listPublishedPosts } from '@/lib/blog';

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? 'https://www.shilikajain.com';

const STATIC_PAGES: { path: string; priority: number; changeFrequency: MetadataRoute.Sitemap[number]['changeFrequency'] }[] = [
  { path: '/', priority: 1.0, changeFrequency: 'weekly' },
  { path: '/about', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/speaker', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/testimonials', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/blog', priority: 0.9, changeFrequency: 'daily' },
  { path: '/playbook', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/glossary', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/authors/shilika-jain', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/services', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/work', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/press', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/faq', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/contact', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/services/web3-pr-campaigns', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/services/token-launch-pr', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/services/ai-startup-pr', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/services/apac-pr', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/services/kol-marketing', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/services/cybersecurity-pr', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/services/founder-profiling', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/services/content-writing', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/work/bullieverse', priority: 0.7, changeFrequency: 'yearly' },
  { path: '/work/fluence', priority: 0.7, changeFrequency: 'yearly' },
  { path: '/work/gaia-ai', priority: 0.7, changeFrequency: 'yearly' },
  { path: '/work/mantra-chain', priority: 0.7, changeFrequency: 'yearly' },
  { path: '/work/rari-chain', priority: 0.7, changeFrequency: 'yearly' },
  { path: '/work/web3auth', priority: 0.7, changeFrequency: 'yearly' },
  { path: '/playbook/tier-1-pr-trap', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/apac-pr-playbook-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/founder-profiling-sprint', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/crypto-pr-cost-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/get-featured-coindesk-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/fractional-vs-agency', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/best-web3-pr-agencies-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/crypto-pr-vs-ai-pr', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/web3-pr-agency-mistakes', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/pre-token-launch-pr-checklist', priority: 0.75, changeFrequency: 'monthly' },
  { path: '/playbook/how-to-pitch-cointelegraph-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/op-eds-vs-press-releases', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/whitepaper-writing-ai-startups-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/how-gaia-ai-got-into-forbes', priority: 0.75, changeFrequency: 'monthly' },
  { path: '/playbook/how-rari-chain-landed-11-tier1-placements', priority: 0.75, changeFrequency: 'monthly' },
  { path: '/playbook/ai-startup-pr-2026', priority: 0.85, changeFrequency: 'monthly' },
  { path: '/playbook/cybersecurity-pr-2026', priority: 0.85, changeFrequency: 'monthly' },
  // AUTO-PLAYBOOKS-15-114
  { path: '/playbook/how-to-get-featured-in-decrypt-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/how-to-get-covered-the-block-blockworks-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/how-to-get-bloomberg-crypto-coverage-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/how-to-get-crypto-project-into-forbes-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/crypto-press-release-distribution-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/best-crypto-press-release-services-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/free-token-listing-press-sites-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/press-coverage-startup-without-investors-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/press-coverage-startup-reddit-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/crypto-media-relations-guide-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/binance-listing-announcement-pr-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/exchange-listing-pr-best-practices-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/token-launch-pr-campaign-cost-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/best-token-launch-marketing-agencies-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/crypto-presale-launchpad-marketing-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/stablecoin-launch-pr-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/nft-project-pr-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/tge-communications-timeline-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/crypto-airdrop-pr-strategy-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/post-tge-pr-first-90-days-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/defi-protocol-pr-strategy-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/best-defi-pr-agency-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/depin-pr-strategy-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/blockchain-gaming-pr-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/web3-infrastructure-pr-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/crypto-exchange-pr-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/rwa-tokenization-pr-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/restaking-pr-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/crypto-crisis-communications-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/ai-x-crypto-agent-pr-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/best-web3-pr-agency-india-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/best-web3-pr-agency-usa-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/best-crypto-pr-agency-singapore-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/crypto-pr-korea-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/crypto-pr-japan-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/crypto-pr-dubai-mena-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/crypto-pr-vietnam-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/token-launch-marketing-agency-india-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/ai-startup-pr-agency-india-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/apac-press-windows-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/ai-product-launch-pr-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/ai-series-a-funding-announcement-pr-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/ai-thought-leadership-pr-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/enterprise-ai-pr-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/healthcare-ai-pr-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/what-is-an-ai-publicist-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/how-to-get-ai-startup-in-techcrunch-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/how-to-get-covered-the-information-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/ai-pr-agency-pricing-packages-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/best-b2b-saas-pr-agencies-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/how-to-build-founder-thought-leadership-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/personal-brand-crypto-founder-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/personal-brand-startup-founder-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/how-to-get-podcast-interviews-founder-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/how-to-submit-op-ed-techcrunch-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/op-ed-ghostwriting-executives-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/how-to-get-speaking-slots-crypto-conferences-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/best-founder-personal-branding-agencies-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/linkedin-strategy-founders-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/how-to-get-into-forbes-councils-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/best-fractional-pr-consultant-tech-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/best-fractional-pr-consultant-web3-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/fractional-pr-cost-pricing-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/fractional-cmo-web3-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/fractional-pr-vs-in-house-hire-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/when-to-hire-fractional-pr-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/best-crypto-kol-marketing-agencies-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/kol-campaign-token-launch-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/crypto-influencer-pricing-rates-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/crypto-kol-marketing-korea-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/how-to-vet-crypto-kols-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/web3-kol-agency-vs-in-house-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/top-crypto-marketing-agencies-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/web3-marketing-agency-guide-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/cybersecurity-pr-agency-pricing-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/how-to-get-covered-dark-reading-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/cybersecurity-analyst-relations-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/cybersecurity-threat-research-pr-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/cybersecurity-breach-crisis-comms-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/best-cybersecurity-marketing-agencies-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/how-to-build-ai-search-visibility-geo-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/how-to-get-cited-by-chatgpt-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/aeo-vs-seo-startups-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/how-to-measure-pr-roi-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/share-of-voice-crypto-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/how-to-choose-web3-pr-agency-checklist-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/web3-pr-agency-reviews-clutch-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/pr-for-tech-startups-guide-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/b2b-tech-pr-guide-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/earned-vs-paid-media-web3-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/crypto-pr-small-budget-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/affordable-pr-tech-startup-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/crypto-publicist-vs-agency-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/how-to-write-crypto-press-release-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/crypto-pr-agency-comparison-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/web3-pr-bear-market-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/crypto-newsjacking-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/founder-led-diy-pr-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/token-launch-pr-mistakes-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/playbook/coindesk-vs-cointelegraph-where-to-pitch-2026', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/glossary/what-is-fractional-pr', priority: 0.65, changeFrequency: 'monthly' },
  { path: '/glossary/what-is-geo-generative-engine-optimization', priority: 0.65, changeFrequency: 'monthly' },
  { path: '/glossary/what-is-a-tge-comms-plan', priority: 0.65, changeFrequency: 'monthly' },
  { path: '/glossary/what-is-aeo-answer-engine-optimization', priority: 0.65, changeFrequency: 'monthly' },
  { path: '/glossary/what-is-a-kol-wave', priority: 0.65, changeFrequency: 'monthly' },
  { path: '/apac', priority: 0.85, changeFrequency: 'monthly' },
  { path: '/india', priority: 0.85, changeFrequency: 'monthly' },
  { path: '/singapore', priority: 0.85, changeFrequency: 'monthly' },
  { path: '/dubai-mena', priority: 0.85, changeFrequency: 'monthly' },
  { path: '/korea', priority: 0.85, changeFrequency: 'monthly' },
  { path: '/japan', priority: 0.85, changeFrequency: 'monthly' },
  // AUTO-LANDING-PAGES
  { path: '/pages', priority: 0.85, changeFrequency: 'weekly' },
  { path: '/pages/web3-pr-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/token-launch-pr-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/ai-startup-pr-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/crypto-kol-marketing-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/cybersecurity-pr-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/founder-personal-branding-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/apac-crypto-pr-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/crypto-content-writing-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/defi-pr-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/nft-pr-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/depin-pr-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/blockchain-gaming-pr-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/web3-infrastructure-pr-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/rwa-tokenization-pr-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/crypto-exchange-pr-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/stablecoin-pr-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/dao-pr-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/metaverse-pr-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/layer2-pr-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/memecoin-marketing-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/web3-pr-agency-india', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/web3-pr-agency-usa', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/crypto-pr-agency-singapore', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/crypto-pr-agency-korea', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/crypto-pr-agency-japan', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/crypto-pr-agency-dubai', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/crypto-pr-agency-uk', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/crypto-pr-agency-vietnam', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/web3-pr-agency-uae', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/crypto-marketing-agency-india', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/tge-pr-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/crypto-token-launch-marketing-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/binance-listing-pr-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/crypto-exchange-listing-pr', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/ico-ido-marketing-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/crypto-presale-marketing-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/airdrop-marketing-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/token-launch-pr-agency-india', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/crypto-press-release-distribution-service', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/crypto-press-release-service', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/web3-kol-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/crypto-influencer-marketing-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/crypto-kol-agency-korea', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/crypto-twitter-kol-marketing', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/crypto-youtube-influencer-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/telegram-marketing-agency-crypto', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/crypto-community-growth-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/crypto-kol-agency-japan', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/ai-pr-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/ai-publicist', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/enterprise-ai-pr-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/healthcare-ai-pr-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/b2b-saas-pr-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/ai-pr-agency-india', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/generative-ai-pr-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/ai-thought-leadership-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/deeptech-pr-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/fintech-ai-pr-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/cybersecurity-marketing-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/cybersecurity-analyst-relations-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/infosec-pr-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/cybersecurity-pr-agency-usa', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/threat-intelligence-pr-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/founder-thought-leadership-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/op-ed-ghostwriting-service', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/crypto-founder-personal-branding', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/linkedin-ghostwriting-for-founders', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/executive-visibility-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/podcast-booking-agency-founders', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/founder-pr-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/fractional-pr-consultant', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/fractional-pr-consultant-web3', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/fractional-cmo-web3', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/fractional-head-of-pr', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/crypto-pr-consultant', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/ai-pr-consultant', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/korea-crypto-pr-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/japan-crypto-pr-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/india-crypto-pr-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/mena-crypto-pr-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/korea-kol-marketing-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/apac-token-launch-pr', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/korea-japan-crypto-pr', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/crypto-whitepaper-writing-service', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/founder-essay-ghostwriting', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/geo-aeo-agency-crypto', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/ai-search-visibility-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/crypto-content-marketing-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/thought-leadership-ghostwriting', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/best-crypto-pr-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/best-web3-marketing-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/top-crypto-marketing-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/crypto-pr-agency-for-startups', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/affordable-crypto-pr-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/crypto-pr-agency-small-budget', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/b2b-tech-pr-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/pr-agency-for-tech-startups', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/web3-marketing-agency', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/crypto-publicist', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pages/token-launch-marketing-agency', priority: 0.8, changeFrequency: 'monthly' },
];

export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  // NOTE: previously this stamped every static page with `lastModified: new Date()`
  // on every request, which told Google literally every page on the site changed
  // every single day. That's a known anti-pattern: it makes the lastmod signal
  // useless and can cause Google to discount it entirely. We omit lastModified for
  // static pages that don't have a real tracked edit date instead of faking one.
  const staticEntries = STATIC_PAGES.map(({ path, priority, changeFrequency }) => ({
    url: `${SITE_URL}${path}`,
    priority,
    changeFrequency,
  }));

  let blogEntries: MetadataRoute.Sitemap = [];
  try {
    const posts = await listPublishedPosts();
    blogEntries = posts.map((p) => ({
      url: `${SITE_URL}/blog/${p.slug}`,
      lastModified: new Date(p.updated_at),
      priority: 0.7,
      changeFrequency: 'monthly' as const,
    }));
  } catch {
    // Supabase not reachable at build time — ship static-only sitemap and let
    // the next revalidation pick up the blog rows.
  }

  return [...staticEntries, ...blogEntries];
}
