#!/usr/bin/env python3
"""Canonical topic plan for 100 commercial-intent /pages landing pages.

Derived from the Decision/commercial queries in the LLM keyword sheet, crossed
with services x regions x verticals. #1 (web3-pr-agency) is hand-built as the
gold-standard template; the rest are generated to match it.
Emits data/landing-pages.json.
"""
import json, os

# service_key -> (canonical form value [must match the form <select> options], eyebrow cat, service page href)
SERVICES = {
    "web3":   ("Web3 PR",                       "WEB3 PR",        "/services/web3-pr-campaigns"),
    "tge":    ("Token Launch / TGE PR",         "TOKEN LAUNCH",   "/services/token-launch-pr"),
    "ai":     ("AI Startup PR",                 "AI PR",          "/services/ai-startup-pr"),
    "apac":   ("APAC Localisation",             "APAC",           "/services/apac-pr"),
    "kol":    ("KOL & Influencer Marketing",    "KOL",            "/services/kol-marketing"),
    "cyber":  ("Cybersecurity PR",              "CYBERSECURITY",  "/services/cybersecurity-pr"),
    "founder":("Founder Profiling & Op-Eds",    "FOUNDER",        "/services/founder-profiling"),
    "content":("Content Writing",               "CONTENT",        "/services/content-writing"),
}

# Each topic: slug, h1, metaTitle, deck, service_key, region, vertical, intent, links[]
# links are hrefs to cross-link (playbooks, services, work, sibling /pages).
T = [
 # A. core service pillars (web3-pr-agency is hand-built; kept here for index + metadata)
 ("web3-pr-agency","The best Web3 PR agency is one senior operator","Best Web3 PR Agency in 2026 | Fractional Senior Operator",
  "Hire a fractional senior Web3 PR operator instead of a $15K-$45K/mo agency. 50+ founders placed across tier-1 crypto and mainstream press.",
  "web3","Global","General","Hire",
  ["/playbook/best-web3-pr-agencies-2026","/playbook/fractional-vs-agency","/services/web3-pr-campaigns","/pages/token-launch-pr-agency"]),
 ("token-launch-pr-agency","Token launch PR that lands in 24 hours","Token Launch & TGE PR Agency 2026 | Shilika Jain",
  "A senior operator who runs your TGE comms end to end: embargo, tier-1 outreach, exchange coordination and a three-wave KOL launch.",
  "tge","Global","Token launch","Hire",
  ["/playbook/pre-token-launch-pr-checklist","/playbook/token-launch-pr-campaign-cost-2026","/services/token-launch-pr","/pages/web3-pr-agency"]),
 ("ai-startup-pr-agency","AI startup PR built on credibility, not hype","AI Startup PR Agency 2026 | Fractional AI Publicist",
  "Tier-1 AI PR from a senior operator: Forbes, TechCrunch, The Information and AI Magazine, plus the AI-search work that gets you cited.",
  "ai","Global","AI","Hire",
  ["/playbook/ai-startup-pr-2026","/playbook/crypto-pr-vs-ai-pr","/services/ai-startup-pr","/pages/ai-pr-agency"]),
 ("crypto-kol-marketing-agency","Crypto KOL marketing with a fraud audit on every creator","Crypto KOL Marketing Agency 2026 | 200+ Vetted Creators",
  "Three-wave KOL launches across 200+ vetted creators, with an independent fraud audit before any creator is booked.",
  "kol","Global","KOL","Hire",
  ["/playbook/best-crypto-kol-marketing-agencies-2026","/playbook/how-to-vet-crypto-kols-2026","/services/kol-marketing","/pages/web3-kol-agency"]),
 ("cybersecurity-pr-agency","Cybersecurity PR that analysts and AI engines cite","Cybersecurity PR Agency 2026 | Analyst-First Comms",
  "Analyst relations, threat-research amplification and tier-1 security press from a fractional senior operator, for less than a Series B retainer.",
  "cyber","Global","Cybersecurity","Hire",
  ["/playbook/cybersecurity-pr-2026","/playbook/cybersecurity-analyst-relations-2026","/services/cybersecurity-pr","/pages/cybersecurity-marketing-agency"]),
 ("founder-personal-branding-agency","Founder personal branding that builds a category voice","Founder Personal Branding Agency 2026 | Shilika Jain",
  "Positioning, op-eds, a podcast tour and an author-entity build that turns a technical founder into the cited voice of their category.",
  "founder","Global","Founder","Hire",
  ["/playbook/founder-profiling-sprint","/playbook/how-to-build-founder-thought-leadership-2026","/services/founder-profiling","/pages/op-ed-ghostwriting-service"]),
 ("apac-crypto-pr-agency","APAC crypto PR with native-language access","APAC Crypto PR Agency 2026 | Korea, Japan, India, MENA",
  "Native placement across Korea, Japan, Vietnam, China, India and MENA, where half of crypto media traffic lives.",
  "apac","APAC","General","Hire",
  ["/playbook/apac-pr-playbook-2026","/playbook/apac-press-windows-2026","/services/apac-pr","/pages/korea-crypto-pr-agency"]),
 ("crypto-content-writing-agency","Ghostwritten op-eds and whitepapers that get cited","Crypto Content Writing Agency 2026 | Op-Eds & Whitepapers",
  "Founder essays, op-eds and whitepapers structured for human readers and AI search, in the founder's own voice.",
  "content","Global","Content","Hire",
  ["/playbook/op-eds-vs-press-releases","/playbook/op-ed-ghostwriting-executives-2026","/services/content-writing","/pages/geo-aeo-agency-crypto"]),

 # B. Web3 PR by vertical
 ("defi-pr-agency","DeFi PR that leads with mechanism, not yield","DeFi PR Agency 2026 | Protocol & Governance Comms",
  "Earn coverage for a DeFi protocol on The Defiant, DL News and tier-1 crypto desks without sounding like every other yield story.",
  "web3","Global","DeFi","Hire",
  ["/playbook/defi-protocol-pr-strategy-2026","/playbook/best-defi-pr-agency-2026","/services/web3-pr-campaigns","/pages/web3-pr-agency"]),
 ("nft-pr-agency","NFT PR for utility, IP and culture","NFT PR Agency 2026 | Beyond the Hype Cycle",
  "Coverage for NFT and digital-IP projects built on utility and culture, with the RARI royalty-enforcement lesson behind it.",
  "web3","Global","NFT","Hire",
  ["/playbook/nft-project-pr-2026","/work/rari-chain","/services/web3-pr-campaigns","/pages/web3-pr-agency"]),
 ("depin-pr-agency","DePIN PR that makes a category a beat","DePIN PR Agency 2026 | Decentralized Infrastructure Comms",
  "Turn decentralized-infrastructure into a publishable category, with the Fluence playbook that anchored DePIN as a tier-1 beat.",
  "web3","Global","DePIN","Hire",
  ["/playbook/depin-pr-strategy-2026","/work/fluence","/services/web3-pr-campaigns","/pages/web3-infrastructure-pr-agency"]),
 ("blockchain-gaming-pr-agency","Web3 gaming PR for two audiences at once","Blockchain Gaming PR Agency 2026 | Dual-Track Comms",
  "Dual-track PR for gamers and crypto media, with the Bullieverse India launch as the worked example.",
  "web3","Global","Gaming","Hire",
  ["/playbook/blockchain-gaming-pr-2026","/work/bullieverse","/services/web3-pr-campaigns","/pages/web3-pr-agency"]),
 ("web3-infrastructure-pr-agency","Infra PR that borrows the partner's credibility","Web3 Infrastructure PR Agency 2026 | Wallets, Oracles, RPCs",
  "Make wallets, oracles, RPCs and middleware newsworthy, with the Web3Auth Google Cloud story as the model.",
  "web3","Global","Infrastructure","Hire",
  ["/playbook/web3-infrastructure-pr-2026","/work/web3auth","/services/web3-pr-campaigns","/pages/depin-pr-agency"]),
 ("rwa-tokenization-pr-agency","RWA PR where TradFi credibility meets crypto reach","RWA & Tokenization PR Agency 2026 | Institutional Credibility",
  "Coverage that institutions and crypto media both take seriously, with the MANTRA $11M Middle East RWA story behind it.",
  "web3","Global","RWA","Hire",
  ["/playbook/rwa-tokenization-pr-2026","/work/mantra-chain","/services/web3-pr-campaigns","/pages/stablecoin-pr-agency"]),
 ("crypto-exchange-pr-agency","Exchange PR built on trust and security","Crypto Exchange PR Agency 2026 | Listings, Security, Access",
  "Comms across listings, security, regulation and regional access, with crisis readiness so one breach does not erase it all.",
  "tge","Global","Exchange","Hire",
  ["/playbook/crypto-exchange-pr-2026","/playbook/crypto-crisis-communications-2026","/services/token-launch-pr","/pages/token-launch-pr-agency"]),
 ("stablecoin-pr-agency","Stablecoin PR that leads with reserves and audits","Stablecoin PR Agency 2026 | Trust-First Comms",
  "A trust-first stablecoin narrative built on reserves, audits and regulation, not yield.",
  "tge","Global","Stablecoin","Hire",
  ["/playbook/stablecoin-launch-pr-2026","/playbook/rwa-tokenization-pr-2026","/services/token-launch-pr","/pages/rwa-tokenization-pr-agency"]),
 ("dao-pr-agency","DAO and governance PR that explains the mechanism","DAO PR Agency 2026 | Governance & Community Comms",
  "Make governance, treasuries and on-chain decision-making legible to editors and the wider community.",
  "web3","Global","DAO","Hire",
  ["/playbook/defi-protocol-pr-strategy-2026","/services/web3-pr-campaigns","/pages/web3-pr-agency","/pages/crypto-community-growth-agency"]),
 ("metaverse-pr-agency","Metaverse and gaming PR beyond the buzzword","Metaverse PR Agency 2026 | Worlds, IP & Communities",
  "Coverage for metaverse and immersive projects grounded in product and community, not 2021 hype.",
  "web3","Global","Metaverse","Hire",
  ["/playbook/blockchain-gaming-pr-2026","/work/bullieverse","/services/web3-pr-campaigns","/pages/blockchain-gaming-pr-agency"]),
 ("layer2-pr-agency","Layer-2 and rollup PR that owns a category word","Layer-2 PR Agency 2026 | Rollups, Appchains, Scaling",
  "Position an L2, rollup or appchain around a category it can own, with the RARI Chain framing lesson.",
  "web3","Global","Layer 2","Hire",
  ["/playbook/web3-infrastructure-pr-2026","/work/rari-chain","/services/web3-pr-campaigns","/pages/web3-infrastructure-pr-agency"]),
 ("memecoin-marketing-agency","Memecoin marketing with a credibility floor","Memecoin Marketing Agency 2026 | Community-First, Compliance-Aware",
  "Community-first memecoin marketing that still respects disclosure and does not torch long-term credibility.",
  "kol","Global","Memecoin","Hire",
  ["/playbook/how-to-vet-crypto-kols-2026","/services/kol-marketing","/pages/crypto-kol-marketing-agency","/pages/crypto-community-growth-agency"]),

 # C. Web3 PR by region
 ("web3-pr-agency-india","Web3 PR agency in India that treats it as a home market","Web3 PR Agency in India 2026 | Inc42, YourStory, ET",
  "Indian home-market PR plus crypto-native reach, with the Bullieverse dual-track launch as the model.",
  "web3","India","General","Hire",
  ["/playbook/best-web3-pr-agency-india-2026","/india","/work/bullieverse","/pages/india-crypto-pr-agency"]),
 ("web3-pr-agency-usa","Web3 PR agency for the US market","Web3 PR Agency USA 2026 | Tier-1 Crypto & Mainstream",
  "Cut through the most crowded crypto press market in the world with a senior operator who pitches, not an account team.",
  "web3","US / EU","General","Hire",
  ["/playbook/best-web3-pr-agency-usa-2026","/playbook/get-featured-coindesk-2026","/services/web3-pr-campaigns","/pages/web3-pr-agency"]),
 ("crypto-pr-agency-singapore","Crypto PR agency in Singapore","Crypto PR Agency Singapore 2026 | Token2049 & SEA Access",
  "Singapore and SEA media plus Token2049 event leverage, from an operator with native APAC access.",
  "apac","Singapore","General","Hire",
  ["/playbook/best-crypto-pr-agency-singapore-2026","/singapore","/services/apac-pr","/pages/apac-crypto-pr-agency"]),
 ("crypto-pr-agency-korea","Crypto PR agency in Korea","Crypto PR Agency Korea 2026 | BloomingBit, TokenPost, KOLs",
  "Native Korean placement and KOL access in the market that drives roughly half of Asia's crypto media traffic.",
  "apac","Korea / Japan","General","Hire",
  ["/playbook/crypto-pr-korea-2026","/korea","/services/apac-pr","/pages/korea-kol-marketing-agency"]),
 ("crypto-pr-agency-japan","Crypto PR agency in Japan","Crypto PR Agency Japan 2026 | CryptoTimes JP, CoinPost",
  "Native Japanese placement and a pitch approach built for how Japanese newsrooms actually work.",
  "apac","Korea / Japan","General","Hire",
  ["/playbook/crypto-pr-japan-2026","/japan","/services/apac-pr","/pages/japan-crypto-pr-agency"]),
 ("crypto-pr-agency-dubai","Crypto PR agency in Dubai and MENA","Crypto PR Agency Dubai & MENA 2026 | VARA, Token2049",
  "MENA placement plus Token2049 Dubai leverage and a VARA-aware regulatory angle.",
  "apac","MENA / Dubai","General","Hire",
  ["/playbook/crypto-pr-dubai-mena-2026","/dubai-mena","/work/mantra-chain","/pages/mena-crypto-pr-agency"]),
 ("crypto-pr-agency-uk","Crypto PR agency in the UK","Crypto PR Agency UK 2026 | London Crypto & Fintech Press",
  "UK and European crypto and fintech coverage from a senior operator with tier-1 relationships.",
  "web3","US / EU","General","Hire",
  ["/playbook/best-web3-pr-agency-usa-2026","/services/web3-pr-campaigns","/pages/web3-pr-agency","/pages/crypto-pr-agency-singapore"]),
 ("crypto-pr-agency-vietnam","Crypto PR agency in Vietnam","Crypto PR Agency Vietnam 2026 | High-Adoption SEA Market",
  "Reach one of the highest crypto-adoption markets on earth with native media and community access.",
  "apac","APAC","General","Hire",
  ["/playbook/crypto-pr-vietnam-2026","/services/apac-pr","/pages/apac-crypto-pr-agency","/pages/crypto-pr-agency-singapore"]),
 ("web3-pr-agency-uae","Web3 PR agency in the UAE","Web3 PR Agency UAE 2026 | Abu Dhabi & Dubai",
  "UAE-based and UAE-targeted Web3 PR with regulatory tailwinds and event-led access.",
  "apac","MENA / Dubai","General","Hire",
  ["/playbook/crypto-pr-dubai-mena-2026","/dubai-mena","/services/apac-pr","/pages/crypto-pr-agency-dubai"]),
 ("crypto-marketing-agency-india","Crypto marketing agency in India","Crypto Marketing Agency India 2026 | PR, KOL & Growth",
  "Full-funnel crypto marketing for Indian and India-targeting projects: PR, KOL and community.",
  "web3","India","General","Hire",
  ["/playbook/best-web3-pr-agency-india-2026","/india","/services/web3-pr-campaigns","/pages/web3-pr-agency-india"]),

 # D. token launch / TGE
 ("tge-pr-agency","TGE PR agency for the eight-week window","TGE PR Agency 2026 | Token Generation Event Comms",
  "A dated comms sequence into and out of your token generation event: narrative, media, KOLs and crisis prep.",
  "tge","Global","Token launch","Hire",
  ["/playbook/tge-communications-timeline-2026","/glossary/what-is-a-tge-comms-plan","/services/token-launch-pr","/pages/token-launch-pr-agency"]),
 ("crypto-token-launch-marketing-agency","Token launch marketing, end to end","Crypto Token Launch Marketing Agency 2026 | PR + KOL",
  "PR, KOL waves and community sequencing timed to one launch cycle, run by the operator doing the work.",
  "tge","Global","Token launch","Hire",
  ["/playbook/best-token-launch-marketing-agencies-2026","/playbook/kol-campaign-token-launch-2026","/services/token-launch-pr","/pages/tge-pr-agency"]),
 ("binance-listing-pr-agency","PR for a Binance listing announcement","Binance Listing PR Agency 2026 | Exchange Announcement Comms",
  "Coordinate the announcement, embargo and KOL wave so a Binance listing actually lands in its 24-hour window.",
  "tge","Global","Exchange","Hire",
  ["/playbook/binance-listing-announcement-pr-2026","/playbook/exchange-listing-pr-best-practices-2026","/services/token-launch-pr","/pages/crypto-exchange-listing-pr"]),
 ("crypto-exchange-listing-pr","Exchange listing PR best practices, executed","Crypto Exchange Listing PR 2026 | Binance, OKX, Bybit",
  "A repeatable listing-announcement playbook across Binance, OKX, Bybit and more, with the compliance lines built in.",
  "tge","Global","Exchange","Hire",
  ["/playbook/exchange-listing-pr-best-practices-2026","/playbook/binance-listing-announcement-pr-2026","/services/token-launch-pr","/pages/binance-listing-pr-agency"]),
 ("ico-ido-marketing-agency","ICO and IDO marketing with a credibility narrative","ICO & IDO Marketing Agency 2026 | Credible Launch Comms",
  "Build demand and credibility around a public sale without the hype-cycle damage that kills long-term trust.",
  "tge","Global","Token launch","Hire",
  ["/playbook/crypto-presale-launchpad-marketing-2026","/services/token-launch-pr","/pages/crypto-presale-marketing-agency","/pages/tge-pr-agency"]),
 ("crypto-presale-marketing-agency","Presale and launchpad marketing","Crypto Presale Marketing Agency 2026 | Launchpad Comms",
  "Demand and credibility around a presale, with KOL and community sequencing that survives the launch.",
  "tge","Global","Token launch","Hire",
  ["/playbook/crypto-presale-launchpad-marketing-2026","/services/token-launch-pr","/pages/ico-ido-marketing-agency","/pages/crypto-kol-marketing-agency"]),
 ("airdrop-marketing-agency","Airdrop marketing that earns real coverage","Airdrop Marketing Agency 2026 | Comms Beyond Farming",
  "Message eligibility, avoid a farming-only narrative and turn an airdrop into an actual press moment.",
  "tge","Global","Token launch","Hire",
  ["/playbook/crypto-airdrop-pr-strategy-2026","/services/token-launch-pr","/pages/token-launch-pr-agency","/pages/crypto-kol-marketing-agency"]),
 ("token-launch-pr-agency-india","Token launch PR agency in India","Token Launch PR Agency India 2026 | Compliant Dual-Track",
  "Launch a token with an Indian base or audience: the compliance reality and a dual-track domestic plus crypto-native launch.",
  "tge","India","Token launch","Hire",
  ["/playbook/token-launch-marketing-agency-india-2026","/india","/services/token-launch-pr","/pages/web3-pr-agency-india"]),
 ("crypto-press-release-distribution-service","Crypto press release distribution that earns pickup","Crypto Press Release Distribution 2026 | Wire vs Earned",
  "Distribution that drives real pickup, not just syndication, paired with direct pitching to the right desks.",
  "content","Global","Press release","Hire",
  ["/playbook/crypto-press-release-distribution-2026","/playbook/how-to-write-crypto-press-release-2026","/services/content-writing","/pages/crypto-press-release-service"]),
 ("crypto-press-release-service","Crypto press release writing and placement","Crypto Press Release Service 2026 | Written to Get Picked Up",
  "Press releases written around a dated news peg and pitched to the reporters who actually cover your beat.",
  "content","Global","Press release","Hire",
  ["/playbook/how-to-write-crypto-press-release-2026","/playbook/crypto-press-release-distribution-2026","/services/content-writing","/pages/crypto-press-release-distribution-service"]),

 # E. KOL / influencer
 ("web3-kol-agency","Web3 KOL agency with vetting built in","Web3 KOL Agency 2026 | 200+ Vetted Creators",
  "Region-segmented creator activation across X, YouTube, Telegram and Farcaster, with a fraud audit on every name.",
  "kol","Global","KOL","Hire",
  ["/playbook/best-crypto-kol-marketing-agencies-2026","/playbook/web3-kol-agency-vs-in-house-2026","/services/kol-marketing","/pages/crypto-kol-marketing-agency"]),
 ("crypto-influencer-marketing-agency","Crypto influencer marketing with real attribution","Crypto Influencer Marketing Agency 2026 | Cost-Per-Wallet",
  "Influencer campaigns measured on cost-per-wallet and on-chain attribution, not vanity reach.",
  "kol","Global","KOL","Hire",
  ["/playbook/crypto-influencer-pricing-rates-2026","/playbook/how-to-vet-crypto-kols-2026","/services/kol-marketing","/pages/web3-kol-agency"]),
 ("crypto-kol-agency-korea","Crypto KOL agency for Korea","Crypto KOL Agency Korea 2026 | Native Creator Access",
  "Activate Korean creators credibly, by Korea's own rules, rates and platforms, with native briefs.",
  "kol","Korea / Japan","KOL","Hire",
  ["/playbook/crypto-kol-marketing-korea-2026","/korea","/services/kol-marketing","/pages/crypto-pr-agency-korea"]),
 ("crypto-twitter-kol-marketing","Crypto Twitter/X KOL marketing","Crypto Twitter KOL Marketing 2026 | X Creator Waves",
  "X-native KOL waves with credibility anchors and disclosure language built in.",
  "kol","Global","KOL","Hire",
  ["/playbook/kol-campaign-token-launch-2026","/services/kol-marketing","/pages/crypto-influencer-marketing-agency","/pages/web3-kol-agency"]),
 ("crypto-youtube-influencer-agency","Crypto YouTube influencer agency","Crypto YouTube Influencer Agency 2026 | Deep-Dive Creators",
  "Long-form YouTube creator partnerships for projects that reward a real explanation, vetted for genuine audiences.",
  "kol","Global","KOL","Hire",
  ["/playbook/crypto-influencer-pricing-rates-2026","/services/kol-marketing","/pages/crypto-influencer-marketing-agency","/pages/web3-kol-agency"]),
 ("telegram-marketing-agency-crypto","Telegram and Discord community marketing","Crypto Telegram Marketing Agency 2026 | Community Seeding",
  "Community seeding, AMA scheduling and moderation that turns a channel into a real audience.",
  "kol","Global","Community","Hire",
  ["/playbook/kol-campaign-token-launch-2026","/services/kol-marketing","/pages/crypto-community-growth-agency","/pages/crypto-kol-marketing-agency"]),
 ("crypto-community-growth-agency","Crypto community growth that compounds","Crypto Community Growth Agency 2026 | Real Audiences",
  "Build a community that converts, with KOL, content and PR working together rather than in silos.",
  "kol","Global","Community","Hire",
  ["/playbook/web3-kol-agency-vs-in-house-2026","/services/kol-marketing","/pages/telegram-marketing-agency-crypto","/pages/crypto-kol-marketing-agency"]),
 ("crypto-kol-agency-japan","Crypto KOL agency for Japan","Crypto KOL Agency Japan 2026 | Native Creator Access",
  "Activate Japanese creators with native briefs and a culturally precise approach.",
  "kol","Korea / Japan","KOL","Hire",
  ["/playbook/crypto-pr-japan-2026","/japan","/services/kol-marketing","/pages/crypto-pr-agency-japan"]),

 # F. AI PR
 ("ai-pr-agency","AI PR agency that wins on credibility","AI PR Agency 2026 | Forbes, TechCrunch, The Information",
  "Tier-1 AI coverage and analyst-grade credibility from a senior operator, plus the AI-search work that gets you cited.",
  "ai","Global","AI","Hire",
  ["/playbook/ai-startup-pr-2026","/playbook/ai-pr-agency-pricing-packages-2026","/services/ai-startup-pr","/pages/ai-startup-pr-agency"]),
 ("ai-publicist","An AI publicist who is a specialist, not a rebadge","AI Publicist 2026 | Specialist AI Founder PR",
  "What an AI publicist should actually deliver, and the senior fractional model that delivers it.",
  "ai","Global","AI","Hire",
  ["/playbook/what-is-an-ai-publicist-2026","/playbook/ai-startup-pr-2026","/services/ai-startup-pr","/pages/ai-pr-agency"]),
 ("enterprise-ai-pr-agency","Enterprise AI PR that reaches the CIO's desk","Enterprise AI PR Agency 2026 | Analyst Relations + Trade Press",
  "Analyst relations, customer proof and trade press that land in the rooms an enterprise buyer actually reads.",
  "ai","Global","AI","Hire",
  ["/playbook/enterprise-ai-pr-2026","/playbook/b2b-saas-pr-agency-2026","/services/ai-startup-pr","/pages/b2b-saas-pr-agency"]),
 ("healthcare-ai-pr-agency","Healthcare AI PR that respects the evidence bar","Healthcare AI PR Agency 2026 | Evidence-Led Comms",
  "Comms that respect clinical evidence, regulation and skeptical reporters, built on credibility first.",
  "ai","Global","AI","Hire",
  ["/playbook/healthcare-ai-pr-2026","/playbook/enterprise-ai-pr-2026","/services/ai-startup-pr","/pages/ai-pr-agency"]),
 ("b2b-saas-pr-agency","B2B SaaS PR for the buying committee","B2B SaaS PR Agency 2026 | Category & Customer Proof",
  "Category narrative, analyst relations and customer proof instead of consumer-style hype.",
  "ai","Global","B2B SaaS","Hire",
  ["/playbook/best-b2b-saas-pr-agencies-2026","/playbook/b2b-tech-pr-guide-2026","/services/ai-startup-pr","/pages/enterprise-ai-pr-agency"]),
 ("ai-pr-agency-india","AI PR agency in India","AI PR Agency India 2026 | Global-From-Day-One",
  "PR that earns both Indian and international tech coverage for a global-facing AI startup.",
  "ai","India","AI","Hire",
  ["/playbook/ai-startup-pr-agency-india-2026","/india","/services/ai-startup-pr","/pages/ai-pr-agency"]),
 ("generative-ai-pr-agency","Generative AI PR that leads with the use case","Generative AI PR Agency 2026 | Use-Case-First Comms",
  "Earn coverage by leading with a concrete use case, not buzzword soup, with the Gaia AI worked example.",
  "ai","Global","AI","Hire",
  ["/playbook/ai-product-launch-pr-2026","/work/gaia-ai","/services/ai-startup-pr","/pages/ai-pr-agency"]),
 ("ai-thought-leadership-agency","AI thought leadership and executive positioning","AI Thought Leadership Agency 2026 | Executive Positioning",
  "Position a technical AI founder as a cited category authority across op-eds, podcasts and analyst rooms.",
  "founder","Global","AI","Hire",
  ["/playbook/ai-thought-leadership-pr-2026","/playbook/how-to-build-founder-thought-leadership-2026","/services/founder-profiling","/pages/founder-personal-branding-agency"]),
 ("deeptech-pr-agency","Deep-tech PR that makes the hard stuff legible","Deep-Tech PR Agency 2026 | Complex Tech, Clear Story",
  "Translate genuinely technical products into stories editors and AI engines can carry.",
  "ai","Global","Deep tech","Hire",
  ["/playbook/restaking-pr-2026","/playbook/ai-startup-pr-2026","/services/ai-startup-pr","/pages/enterprise-ai-pr-agency"]),
 ("fintech-ai-pr-agency","Fintech and AI PR at the regulated edge","Fintech AI PR Agency 2026 | Regulated, Credible Comms",
  "Credibility-led PR for fintech and AI products where trust and regulation shape every message.",
  "ai","Global","Fintech","Hire",
  ["/playbook/enterprise-ai-pr-2026","/playbook/b2b-saas-pr-agency-2026","/services/ai-startup-pr","/pages/b2b-saas-pr-agency"]),

 # G. Cybersecurity
 ("cybersecurity-marketing-agency","Cybersecurity marketing built on credibility","Cybersecurity Marketing Agency 2026 | Analyst-Literate",
  "Marketing for security vendors that understands analysts, threat research and the trust game.",
  "cyber","Global","Cybersecurity","Hire",
  ["/playbook/best-cybersecurity-marketing-agencies-2026","/playbook/cybersecurity-pr-2026","/services/cybersecurity-pr","/pages/cybersecurity-pr-agency"]),
 ("cybersecurity-analyst-relations-agency","Analyst relations for Gartner, Forrester and IDC","Cybersecurity Analyst Relations Agency 2026 | MQ & Wave",
  "Briefing cadence and positioning that earns Magic Quadrant and Wave consideration before press even runs.",
  "cyber","Global","Cybersecurity","Hire",
  ["/playbook/cybersecurity-analyst-relations-2026","/playbook/cybersecurity-pr-2026","/services/cybersecurity-pr","/pages/cybersecurity-pr-agency"]),
 ("infosec-pr-agency","InfoSec PR led by threat research","InfoSec PR Agency 2026 | Research-Led Coverage",
  "Turn vulnerability research into coverage on Dark Reading and named security desks, without crossing disclosure lines.",
  "cyber","Global","Cybersecurity","Hire",
  ["/playbook/cybersecurity-threat-research-pr-2026","/playbook/how-to-get-covered-dark-reading-2026","/services/cybersecurity-pr","/pages/cybersecurity-marketing-agency"]),
 ("cybersecurity-pr-agency-usa","Cybersecurity PR agency for the US market","Cybersecurity PR Agency USA 2026 | Security Press & Analysts",
  "US security press and analyst access from a senior operator, for less than a Series B agency retainer.",
  "cyber","US / EU","Cybersecurity","Hire",
  ["/playbook/cybersecurity-pr-2026","/playbook/cybersecurity-pr-agency-pricing-2026","/services/cybersecurity-pr","/pages/cybersecurity-pr-agency"]),
 ("threat-intelligence-pr-agency","PR that amplifies threat intelligence","Threat Intelligence PR Agency 2026 | Research Amplification",
  "Package and place threat-intel findings for maximum credible reach, with coordinated disclosure.",
  "cyber","Global","Cybersecurity","Hire",
  ["/playbook/cybersecurity-threat-research-pr-2026","/playbook/cybersecurity-breach-crisis-comms-2026","/services/cybersecurity-pr","/pages/infosec-pr-agency"]),

 # H. founder / thought leadership
 ("founder-thought-leadership-agency","Founder thought leadership that gets cited","Founder Thought Leadership Agency 2026 | Earned Authority",
  "The cadence, channels and author-entity build that turn a founder into a cited authority, not a LinkedIn poster.",
  "founder","Global","Founder","Hire",
  ["/playbook/how-to-build-founder-thought-leadership-2026","/playbook/founder-profiling-sprint","/services/founder-profiling","/pages/founder-personal-branding-agency"]),
 ("op-ed-ghostwriting-service","Op-ed ghostwriting for founders and executives","Op-Ed Ghostwriting Service 2026 | Editor-Ready Founder Essays",
  "Your name, your thinking, an editor-ready op-ed placed on a real opinion desk, in your voice.",
  "content","Global","Content","Hire",
  ["/playbook/op-ed-ghostwriting-executives-2026","/playbook/op-eds-vs-press-releases","/services/content-writing","/pages/crypto-content-writing-agency"]),
 ("crypto-founder-personal-branding","Personal branding for crypto founders","Crypto Founder Personal Branding 2026 | X + LinkedIn",
  "An X and LinkedIn system that builds authority and still sounds like you, not a content mill.",
  "founder","Global","Founder","Hire",
  ["/playbook/personal-brand-crypto-founder-2026","/playbook/linkedin-strategy-founders-2026","/services/founder-profiling","/pages/founder-personal-branding-agency"]),
 ("linkedin-ghostwriting-for-founders","LinkedIn ghostwriting for founders","LinkedIn Ghostwriting for Founders 2026 | Authority, Not Cringe",
  "A LinkedIn content system tuned to the 2026 algorithm that builds authority without the motivational-account vibe.",
  "founder","Global","Founder","Hire",
  ["/playbook/linkedin-strategy-founders-2026","/playbook/personal-brand-startup-founder-2026","/services/founder-profiling","/pages/crypto-founder-personal-branding"]),
 ("executive-visibility-agency","Executive visibility and positioning","Executive Visibility Agency 2026 | Category Authority",
  "Make a founder or executive the named authority their category and AI engines both recognise.",
  "founder","Global","Founder","Hire",
  ["/playbook/how-to-build-founder-thought-leadership-2026","/playbook/ai-thought-leadership-pr-2026","/services/founder-profiling","/pages/founder-thought-leadership-agency"]),
 ("podcast-booking-agency-founders","Podcast booking for founders","Founder Podcast Booking Agency 2026 | Curated Tours",
  "A curated podcast tour that turns one quarter into lasting authority, with the Gaia AI six-show tour as the model.",
  "founder","Global","Founder","Hire",
  ["/playbook/how-to-get-podcast-interviews-founder-2026","/work/gaia-ai","/services/founder-profiling","/pages/founder-personal-branding-agency"]),
 ("founder-pr-agency","Founder PR that builds the person, not just the company","Founder PR Agency 2026 | Profiles, Op-Eds, Speaking",
  "Profiles, op-eds, podcasts and speaking that make the founder a category voice.",
  "founder","Global","Founder","Hire",
  ["/playbook/founder-profiling-sprint","/playbook/how-to-get-speaking-slots-crypto-conferences-2026","/services/founder-profiling","/pages/founder-thought-leadership-agency"]),

 # I. fractional / consultant
 ("fractional-pr-consultant","A fractional PR consultant, senior on day one","Fractional PR Consultant 2026 | Senior, Embedded, Affordable",
  "A senior PR operator embedded part-time like a team member, for a fraction of an agency retainer.",
  "web3","Global","Fractional","Hire",
  ["/glossary/what-is-fractional-pr","/playbook/best-fractional-pr-consultant-tech-2026","/services/web3-pr-campaigns","/pages/fractional-pr-consultant-web3"]),
 ("fractional-pr-consultant-web3","Fractional PR consultant for Web3 startups","Fractional PR Consultant Web3 2026 | Crypto-Native Senior",
  "Web3 moves too fast for agency layers. A senior fractional operator who runs your PR directly.",
  "web3","Global","Fractional","Hire",
  ["/playbook/best-fractional-pr-consultant-web3-2026","/playbook/fractional-vs-agency","/services/web3-pr-campaigns","/pages/fractional-pr-consultant"]),
 ("fractional-cmo-web3","Fractional CMO for a Web3 startup","Fractional CMO Web3 2026 | When You Need One",
  "A fractional CMO owns the whole growth function. When that fits, when fractional PR fits, and the overlap.",
  "web3","Global","Fractional","Hire",
  ["/playbook/fractional-cmo-web3-2026","/playbook/fractional-vs-agency","/services/web3-pr-campaigns","/pages/fractional-pr-consultant-web3"]),
 ("fractional-head-of-pr","A fractional Head of PR for your stage","Fractional Head of PR 2026 | Senior Comms Leadership",
  "Senior comms leadership without a full-time hire, embedded and accountable.",
  "web3","Global","Fractional","Hire",
  ["/playbook/fractional-pr-vs-in-house-hire-2026","/playbook/when-to-hire-fractional-pr-2026","/services/web3-pr-campaigns","/pages/fractional-pr-consultant"]),
 ("crypto-pr-consultant","A crypto PR consultant who pitches","Crypto PR Consultant 2026 | Senior Operator, Direct",
  "A senior crypto PR consultant who builds the relationships and pitches the editors personally.",
  "web3","Global","Fractional","Hire",
  ["/glossary/what-is-fractional-pr","/playbook/crypto-publicist-vs-agency-2026","/services/web3-pr-campaigns","/pages/crypto-publicist"]),
 ("ai-pr-consultant","An AI PR consultant for technical founders","AI PR Consultant 2026 | Senior, Specialist, Fractional",
  "A senior AI PR consultant who runs your media strategy directly and gets the technical story right.",
  "ai","Global","Fractional","Hire",
  ["/playbook/ai-pr-agency-pricing-packages-2026","/playbook/ai-startup-pr-2026","/services/ai-startup-pr","/pages/ai-publicist"]),

 # J. APAC granular
 ("korea-crypto-pr-agency","Korea crypto PR, native and event-led","Korea Crypto PR Agency 2026 | KBW, BloomingBit, KOLs",
  "Native Korean placement, KOL access and Korea Blockchain Week leverage in Asia's biggest crypto media market.",
  "apac","Korea / Japan","General","Hire",
  ["/playbook/crypto-pr-korea-2026","/korea","/services/apac-pr","/pages/crypto-pr-agency-korea"]),
 ("japan-crypto-pr-agency","Japan crypto PR, precise and process-led","Japan Crypto PR Agency 2026 | Native Outlets & Norms",
  "Native Japanese placement and a pitch approach built for how Japanese newsrooms and regulators work.",
  "apac","Korea / Japan","General","Hire",
  ["/playbook/crypto-pr-japan-2026","/japan","/services/apac-pr","/pages/crypto-pr-agency-japan"]),
 ("india-crypto-pr-agency","India crypto PR as a home market","India Crypto PR Agency 2026 | Inc42, ET, Dual-Track",
  "Home-market Indian coverage plus crypto-native reach, with a compliance-aware dual-track launch.",
  "apac","India","General","Hire",
  ["/playbook/best-web3-pr-agency-india-2026","/india","/services/apac-pr","/pages/web3-pr-agency-india"]),
 ("mena-crypto-pr-agency","MENA crypto PR with regulatory tailwinds","MENA Crypto PR Agency 2026 | Dubai, Abu Dhabi, VARA",
  "MENA placement, VARA-aware framing and Token2049 Dubai leverage, with the MANTRA RWA story behind it.",
  "apac","MENA / Dubai","General","Hire",
  ["/playbook/crypto-pr-dubai-mena-2026","/dubai-mena","/services/apac-pr","/pages/crypto-pr-agency-dubai"]),
 ("korea-kol-marketing-agency","Korea KOL marketing, native and vetted","Korea KOL Marketing Agency 2026 | Native Creator Waves",
  "Korean creator activation by Korea's own rules, rates and platforms, with native briefs and disclosure.",
  "kol","Korea / Japan","KOL","Hire",
  ["/playbook/crypto-kol-marketing-korea-2026","/korea","/services/kol-marketing","/pages/crypto-kol-agency-korea"]),
 ("apac-token-launch-pr","APAC token launch PR across press windows","APAC Token Launch PR 2026 | Korea, Japan, SEA Timing",
  "Time a TGE across the three APAC press windows with coordinated translation and regional KOLs.",
  "apac","APAC","Token launch","Hire",
  ["/playbook/apac-press-windows-2026","/playbook/tge-communications-timeline-2026","/services/apac-pr","/pages/token-launch-pr-agency"]),
 ("korea-japan-crypto-pr","Korea and Japan crypto PR, run together","Korea & Japan Crypto PR 2026 | Dual-Market Access",
  "Coordinated native coverage across the two highest-value, highest-bar APAC crypto markets.",
  "apac","Korea / Japan","General","Hire",
  ["/playbook/crypto-pr-korea-2026","/playbook/crypto-pr-japan-2026","/services/apac-pr","/pages/apac-crypto-pr-agency"]),

 # K. content / GEO
 ("crypto-whitepaper-writing-service","Whitepaper writing that earns trust","Crypto Whitepaper Writing Service 2026 | Clear, Credible",
  "A whitepaper sprint that turns a technical thesis into a document investors and media actually read.",
  "content","Global","Content","Hire",
  ["/playbook/op-eds-vs-press-releases","/services/content-writing","/pages/crypto-content-writing-agency","/pages/founder-essay-ghostwriting"]),
 ("founder-essay-ghostwriting","Founder essay ghostwriting in your voice","Founder Essay Ghostwriting 2026 | Original, Cited Content",
  "Founder essays written in your voice and structured for human readers and AI search.",
  "content","Global","Content","Hire",
  ["/playbook/op-ed-ghostwriting-executives-2026","/services/content-writing","/pages/op-ed-ghostwriting-service","/pages/crypto-content-writing-agency"]),
 ("geo-aeo-agency-crypto","GEO/AEO so AI engines cite you by name","GEO & AEO Agency 2026 | Get Cited by ChatGPT & Perplexity",
  "Earned media, entity and content work so ChatGPT, Perplexity and Google AI Mode name your brand in the answer.",
  "content","Global","GEO/AEO","Hire",
  ["/playbook/how-to-build-ai-search-visibility-geo-2026","/glossary/what-is-geo-generative-engine-optimization","/services/content-writing","/pages/ai-search-visibility-agency"]),
 ("ai-search-visibility-agency","AI search visibility for startups","AI Search Visibility Agency 2026 | Be the Cited Answer",
  "Make your startup the brand AI engines name when a buyer asks who does what you do.",
  "content","Global","GEO/AEO","Hire",
  ["/playbook/how-to-get-cited-by-chatgpt-2026","/playbook/aeo-vs-seo-startups-2026","/services/content-writing","/pages/geo-aeo-agency-crypto"]),
 ("crypto-content-marketing-agency","Crypto content marketing that compounds","Crypto Content Marketing Agency 2026 | Earned + Owned",
  "Content built to earn coverage and get cited, not just fill a blog, integrated with PR.",
  "content","Global","Content","Hire",
  ["/playbook/op-eds-vs-press-releases","/playbook/how-to-build-ai-search-visibility-geo-2026","/services/content-writing","/pages/geo-aeo-agency-crypto"]),
 ("thought-leadership-ghostwriting","Thought-leadership ghostwriting that holds up","Thought Leadership Ghostwriting 2026 | Defensible POV",
  "Ghostwritten essays built on a genuine, defensible point of view, placed on real desks.",
  "content","Global","Content","Hire",
  ["/playbook/op-ed-ghostwriting-executives-2026","/playbook/how-to-build-founder-thought-leadership-2026","/services/content-writing","/pages/op-ed-ghostwriting-service"]),

 # L. comparison / decision
 ("best-crypto-pr-agency","The best crypto PR agency, chosen honestly","Best Crypto PR Agency 2026 | Honest Criteria & Alternative",
  "What separates real access from a logo wall, and why a senior fractional operator beats most agencies.",
  "web3","Global","General","Decision",
  ["/playbook/best-web3-pr-agencies-2026","/playbook/crypto-pr-agency-comparison-2026","/services/web3-pr-campaigns","/pages/web3-pr-agency"]),
 ("best-web3-marketing-agency","The best Web3 marketing agency for your stage","Best Web3 Marketing Agency 2026 | PR, KOL, Growth",
  "How to choose a Web3 marketing partner by what you actually need, with the red flags to avoid.",
  "web3","Global","General","Decision",
  ["/playbook/web3-marketing-agency-guide-2026","/playbook/top-crypto-marketing-agencies-2026","/services/web3-pr-campaigns","/pages/web3-marketing-agency"]),
 ("top-crypto-marketing-agency","Top crypto marketing agencies, compared","Top Crypto Marketing Agency 2026 | How to Compare",
  "A map of the field and how to choose between PR, growth and KOL specialists.",
  "web3","Global","General","Decision",
  ["/playbook/top-crypto-marketing-agencies-2026","/playbook/web3-marketing-agency-guide-2026","/services/web3-pr-campaigns","/pages/best-web3-marketing-agency"]),
 ("crypto-pr-agency-for-startups","Crypto PR agency for early startups","Crypto PR Agency for Startups 2026 | Lean, Senior, Effective",
  "PR that fits an early startup: when to start, what to spend, and what actually earns coverage.",
  "web3","Global","General","Decision",
  ["/playbook/pr-for-tech-startups-2026","/playbook/crypto-pr-small-budget-2026","/services/web3-pr-campaigns","/pages/affordable-crypto-pr-agency"]),
 ("affordable-crypto-pr-agency","Affordable crypto PR that still earns coverage","Affordable Crypto PR Agency 2026 | Lean Budget, Real Results",
  "What affordable PR really buys, the models that fit a small budget, and the cheap traps to avoid.",
  "web3","Global","General","Decision",
  ["/playbook/affordable-pr-tech-startup-2026","/playbook/crypto-pr-small-budget-2026","/services/web3-pr-campaigns","/pages/crypto-pr-agency-small-budget"]),
 ("crypto-pr-agency-small-budget","Crypto PR on a small budget","Crypto PR Agency Small Budget 2026 | High-Leverage Moves",
  "The high-leverage PR moves a lean team can run, and where to spend the first dollar.",
  "web3","Global","General","Decision",
  ["/playbook/crypto-pr-small-budget-2026","/playbook/founder-led-diy-pr-2026","/services/web3-pr-campaigns","/pages/affordable-crypto-pr-agency"]),
 ("b2b-tech-pr-agency","B2B tech PR for a buying committee","B2B Tech PR Agency 2026 | Category, Analysts, Proof",
  "B2B PR that sells to a committee, not a crowd, with category narrative and customer proof.",
  "ai","Global","B2B","Decision",
  ["/playbook/b2b-tech-pr-guide-2026","/playbook/best-b2b-saas-pr-agencies-2026","/services/ai-startup-pr","/pages/b2b-saas-pr-agency"]),
 ("pr-agency-for-tech-startups","PR agency for tech startups, demystified","PR Agency for Tech Startups 2026 | A Founder's Guide",
  "The whole PR picture for an early tech startup, and the fractional alternative to a full agency.",
  "ai","Global","General","Decision",
  ["/playbook/pr-for-tech-startups-2026","/playbook/fractional-vs-agency","/services/ai-startup-pr","/pages/crypto-pr-agency-for-startups"]),
 ("web3-marketing-agency","Web3 marketing agency, the buyer's guide","Web3 Marketing Agency 2026 | Vetting Questions & Red Flags",
  "The questions that expose real depth, the red flags, and how to match model to stage.",
  "web3","Global","General","Decision",
  ["/playbook/web3-marketing-agency-guide-2026","/playbook/web3-pr-agency-mistakes","/services/web3-pr-campaigns","/pages/best-web3-marketing-agency"]),
 ("crypto-publicist","A crypto publicist vs a PR agency","Crypto Publicist 2026 | Senior Attention vs Agency Bench",
  "What a solo publicist gives you that an agency cannot, and which fits your stage and budget.",
  "web3","Global","General","Decision",
  ["/playbook/crypto-publicist-vs-agency-2026","/glossary/what-is-fractional-pr","/services/web3-pr-campaigns","/pages/crypto-pr-consultant"]),
 ("token-launch-marketing-agency","Token launch marketing agency, chosen well","Token Launch Marketing Agency 2026 | Criteria & Alternative",
  "Criteria for picking a token-launch partner, the trade-offs of each model, and a fractional alternative.",
  "tge","Global","Token launch","Decision",
  ["/playbook/best-token-launch-marketing-agencies-2026","/playbook/fractional-vs-agency","/services/token-launch-pr","/pages/token-launch-pr-agency"]),
]

assert len(T) == 100, f"expected 100, got {len(T)}"
slugs = [t[0] for t in T]
assert len(set(slugs)) == 100, "duplicate slugs: " + str([s for s in slugs if slugs.count(s) > 1])

out = []
for i, (slug, h1, metaTitle, deck, skey, region, vertical, intent, links) in enumerate(T):
    val, cat, svc_href = SERVICES[skey]
    # ensure the service page is among cross-links
    links = list(links)
    if svc_href not in links:
        links.append(svc_href)
    out.append({
        "n": i + 1,
        "slug": slug,
        "h1": h1,
        "title": metaTitle,
        "deck": deck,
        "serviceKey": skey,
        "service": val,
        "cat": cat,
        "servicePage": svc_href,
        "region": region,
        "vertical": vertical,
        "intent": intent,
        "links": links,
    })

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
path = os.path.join(root, "data", "landing-pages.json")
with open(path, "w") as f:
    json.dump(out, f, indent=2, ensure_ascii=False)
print(f"wrote {len(out)} landing-page topics -> {path}")
# quick distribution
from collections import Counter
print("by service:", dict(Counter(o["service"] for o in out)))
print("by region:", dict(Counter(o["region"] for o in out)))
