#!/usr/bin/env python3
"""Canonical topic plan for playbooks 015-114.

Deduped + expanded from "Shilika LLM keywords.xlsx", prioritising long-tail
queries, avoiding the 14 topics already covered by playbooks 001-014.
Emits data/playbook-topics.json, consumed by both the generation workflow and
the wiring script (scripts/wire-playbooks.py).
"""
import json, os

START_N = 15  # playbooks 015..114

# (slug, title, deck, tag, cat, time, primary_keyword, angle, links)
# tag = card label (titlecase); cat = uppercase eyebrow on the article header.
# links = suggested internal hrefs (the writer must use 3-5 of these naturally).
SVC = {
    "web3": "/services/web3-pr-campaigns",
    "tge": "/services/token-launch-pr",
    "ai": "/services/ai-startup-pr",
    "apac": "/services/apac-pr",
    "kol": "/services/kol-marketing",
    "cyber": "/services/cybersecurity-pr",
    "founder": "/services/founder-profiling",
    "content": "/services/content-writing",
}
PB = lambda s: f"/playbook/{s}"
GL = {
    "frac": "/glossary/what-is-fractional-pr",
    "geo": "/glossary/what-is-geo-generative-engine-optimization",
    "tge": "/glossary/what-is-a-tge-comms-plan",
}

T = [
 # ---- Cluster 1: media & outlet pitch guides ----
 ("how-to-get-featured-in-decrypt-2026","How to Get Featured in Decrypt in 2026: Pitch Guide",
  "What Decrypt's editors filter for, the explainer-friendly angle that lands, and a pitch template from a senior Web3 operator's playbook.","Tier-1","TIER-1",9,
  "how to get featured in crypto media","Decrypt-specific newsroom map, what their desk covers vs CoinDesk/Cointelegraph, pitch template, two worked examples.",
  [PB("get-featured-coindesk-2026"),PB("how-to-pitch-cointelegraph-2026"),SVC["web3"],"/work/web3auth"]),
 ("how-to-get-covered-the-block-blockworks-2026","How to Get Covered by The Block and Blockworks in 2026",
  "The two outlets that move institutional crypto. What their reporters cover, why data and primary sourcing win, and how to pitch each.","Tier-1","TIER-1",9,
  "how to get featured in crypto media","The Block (data/scoop culture) vs Blockworks (institutional/markets), reporter mapping, what gets passed.",
  [PB("get-featured-coindesk-2026"),PB("tier-1-pr-trap"),SVC["web3"],"/work/rari-chain"]),
 ("how-to-get-bloomberg-crypto-coverage-2026","How to Get Bloomberg Crypto Coverage in 2026",
  "Bloomberg is the hardest room in crypto. What clears the bar, the data and named-source threshold, and a realistic path for a startup.","Tier-1","TIER-1",9,
  "how to get Bloomberg crypto coverage","Why mainstream business press is different, the verification bar, when to even try, and the institutional angle.",
  [PB("tier-1-pr-trap"),PB("crypto-pr-vs-ai-pr"),SVC["web3"],"/work/mantra-chain"]),
 ("how-to-get-crypto-project-into-forbes-2026","How to Get Your Crypto Project Into Forbes in 2026",
  "Forbes staff vs Forbes Councils vs contributors, what each is worth, and how to earn a real editorial feature instead of a pay-to-play byline.","Tier-1","TIER-1",10,
  "how to get featured in crypto media","Forbes structure decoded, the credibility trap of councils, how Gaia AI earned a real Forbes feature.",
  [PB("tier-1-pr-trap"),SVC["ai"],"/work/gaia-ai",PB("op-eds-vs-press-releases")]),
 ("crypto-press-release-distribution-2026","Crypto Press Release Distribution in 2026: What Actually Works",
  "Wires, crypto-native PR networks, and direct pitching compared. Where distribution helps, where it is theatre, and what editors actually read.","Strategy","PRESS",9,
  "Web3 press release","Distribution channels compared, the difference between pickup and coverage, when a wire is worth it.",
  [SVC["web3"],PB("op-eds-vs-press-releases"),"how-to-write-crypto-press-release-2026",PB("crypto-pr-cost-2026")]),
 ("best-crypto-press-release-services-2026","Best Crypto Press Release Services Compared in 2026",
  "A criteria-led look at the main crypto PR-distribution services, what they really deliver, and the cheaper earned-media alternative.","Pricing","PRESS",8,
  "Web3 press release","Named services compared on reach/quality/cost, the syndication-vs-coverage distinction, decision guide.",
  [SVC["web3"],PB("best-web3-pr-agencies-2026"),"crypto-press-release-distribution-2026",PB("crypto-pr-cost-2026")]),
 ("free-token-listing-press-sites-2026","Free Token Listing and Press Release Sites: Worth It in 2026?",
  "The honest read on free listing and PR sites: what they do for visibility, where they hurt credibility, and what to use instead.","Launch","PRESS",7,
  "Token listing PR campaign","Free vs paid listing sites, SEO/credibility trade-offs, what actually moves a launch.",
  [SVC["tge"],PB("pre-token-launch-pr-checklist"),"crypto-press-release-distribution-2026",GL["tge"]]),
 ("press-coverage-startup-without-investors-2026","How to Get Press Coverage for a Startup Without Investors",
  "No raise, no logo, no problem. The angles that earn coverage when you cannot lead with funding, drawn from real launches.","Strategy","STRATEGY",9,
  "How to get media coverage Web3","Non-funding news hooks, product/data/founder angles, the bootstrapped-startup pitch.",
  [PB("tier-1-pr-trap"),SVC["web3"],"press-coverage-startup-reddit-2026",PB("op-eds-vs-press-releases")]),
 ("press-coverage-startup-reddit-2026","How to Get Press Coverage for a Startup: What Reddit Gets Right and Wrong",
  "The most-upvoted PR advice on Reddit, fact-checked by an operator. What holds up, what wastes your time, and what to do instead.","Strategy","STRATEGY",8,
  "How to get media coverage Web3","Myth-busting common forum advice (HARO, spray-and-pray, paid placement) with the operator correction.",
  [PB("web3-pr-agency-mistakes"),SVC["web3"],"press-coverage-startup-without-investors-2026",PB("crypto-pr-cost-2026")]),
 ("crypto-media-relations-guide-2026","Crypto Media Relations in 2026: Building Real Journalist Relationships",
  "Coverage is a relationship, not a transaction. How to build a real journalist network, what to never do, and how trust compounds.","Strategy","MEDIA",9,
  "Crypto media relations","The relationship model vs transactional pitching, embargo trust, being a useful source.",
  [PB("get-featured-coindesk-2026"),PB("how-to-pitch-cointelegraph-2026"),SVC["web3"],"how-to-get-featured-in-decrypt-2026"]),

 # ---- Cluster 2: token launch / TGE ----
 ("binance-listing-announcement-pr-2026","How to Announce a Binance Listing: PR Strategy for 2026",
  "An exchange listing is a 24-hour window. How to coordinate the announcement, the embargo, and the KOL wave so the listing actually lands.","Launch","LAUNCH",10,
  "Crypto PR for Binance listing announcement","Listing-day comms choreography, compliance-safe messaging, exchange coordination, KOL timing.",
  [SVC["tge"],PB("pre-token-launch-pr-checklist"),SVC["kol"],GL["tge"]]),
 ("exchange-listing-pr-best-practices-2026","Crypto Exchange Listing Announcement PR: Best Practices for 2026",
  "Binance, OKX, Bybit, KuCoin and the rest. The repeatable listing-announcement playbook and the compliance lines you cannot cross.","Launch","LAUNCH",9,
  "Crypto PR","Multi-exchange listing comms framework, no-price/no-projection rules, regional translation.",
  [SVC["tge"],"binance-listing-announcement-pr-2026",PB("pre-token-launch-pr-checklist"),SVC["apac"]]),
 ("token-launch-pr-campaign-cost-2026","What a Token Launch PR Campaign Costs in 2026",
  "Sprint vs retainer vs full launch-plus-tail, what each tier buys, and the hidden line items in a TGE budget.","Pricing","PRICING",9,
  "Token launch PR","TGE-specific pricing tiers, KOL budget, the launch-plus-90-day tail, where money is wasted.",
  [PB("crypto-pr-cost-2026"),SVC["tge"],PB("pre-token-launch-pr-checklist"),SVC["kol"]]),
 ("best-token-launch-marketing-agencies-2026","Best Token Launch Marketing Agencies in 2026: a Field Guide",
  "A criteria-led look at token-launch and TGE agencies, the trade-offs of each model, and a fractional-operator alternative.","Field guide","LAUNCH",10,
  "Token launch PR agency","Criteria for picking a TGE agency, agency vs fractional, conflict-of-interest disclosure.",
  [PB("best-web3-pr-agencies-2026"),SVC["tge"],PB("fractional-vs-agency"),GL["tge"]]),
 ("crypto-presale-launchpad-marketing-2026","Crypto Presale and Launchpad Marketing Playbook for 2026",
  "Launchpads bring liquidity, not narrative. How to build demand and credibility around a presale without the usual hype-cycle damage.","Launch","LAUNCH",9,
  "Crypto PR","Presale/launchpad comms, building a credible narrative pre-token, KOL and community sequencing.",
  [SVC["tge"],SVC["kol"],PB("pre-token-launch-pr-checklist"),PB("token-launch-pr-campaign-cost-2026" if False else "best-token-launch-marketing-agencies-2026")]),
 ("stablecoin-launch-pr-2026","PR for a Stablecoin Launch in 2026",
  "Stablecoins are a trust product. How to run comms that lead with reserves, audits and regulation instead of yield, and earn serious coverage.","Strategy","LAUNCH",9,
  "Stablecoin project PR agency","Trust-first stablecoin narrative, reserve/audit transparency, regulatory framing, the RWA adjacency.",
  [SVC["tge"],"rwa-tokenization-pr-2026",PB("crypto-pr-vs-ai-pr"),"/work/mantra-chain"]),
 ("nft-project-pr-2026","PR for an NFT Project in 2026: Beyond the Hype Cycle",
  "NFTs grew up. How to earn coverage for utility, IP and culture now that the speculative wave is over, with named outlets and angles.","Strategy","STRATEGY",8,
  "Stablecoin project PR agency","Post-hype NFT narrative, utility/IP/culture angles, NFTNow and culture desks, the RARI royalty lesson.",
  [SVC["web3"],"/work/rari-chain",PB("tier-1-pr-trap"),SVC["kol"]]),
 ("tge-communications-timeline-2026","The TGE Communications Timeline for 2026: Week by Week",
  "An eight-week, dated comms timeline into and out of a token generation event, mapping narrative, media, KOLs and crisis prep to the calendar.","Launch","LAUNCH",10,
  "TGE PR","Week-by-week TGE calendar, who does what when, the difference vs the 25-step checklist.",
  [GL["tge"],PB("pre-token-launch-pr-checklist"),SVC["tge"],"post-tge-pr-first-90-days-2026"]),
 ("crypto-airdrop-pr-strategy-2026","Airdrop PR and Comms Strategy for 2026",
  "Airdrops are a comms event, not just a distribution mechanic. How to message eligibility, avoid a farming-only narrative, and earn real coverage.","Launch","LAUNCH",8,
  "Crypto PR","Airdrop messaging, sybil/farming narrative risk, coordinating announcement and KOLs, compliance.",
  [SVC["tge"],SVC["kol"],PB("pre-token-launch-pr-checklist"),GL["tge"]]),
 ("post-tge-pr-first-90-days-2026","Post-TGE PR: The First 90 Days After Listing",
  "Most teams go quiet after the token lands. The sustained-coverage playbook that keeps momentum, sentiment and AI-citation share alive.","Launch","LAUNCH",9,
  "TGE PR","Post-launch sustained coverage, sentiment tracking, the silence trap, milestone cadence.",
  [SVC["tge"],"tge-communications-timeline-2026",PB("crypto-pr-cost-2026"),GL["geo"]]),

 # ---- Cluster 3: Web3 PR by vertical ----
 ("defi-protocol-pr-strategy-2026","How to Get Media Coverage for a DeFi Protocol in 2026",
  "DeFi coverage rewards mechanism clarity and real TVL. How to pitch a protocol without sounding like every other yield story.","Strategy","STRATEGY",9,
  "DeFi PR","DeFi-specific angles (mechanism, security, TVL, governance), what The Defiant/DL News cover, named-source bar.",
  [SVC["web3"],"best-defi-pr-agency-2026",PB("get-featured-coindesk-2026"),"crypto-crisis-communications-2026"]),
 ("best-defi-pr-agency-2026","Best DeFi PR Agencies in 2026: an Honest Comparison",
  "A criteria-led look at agencies that actually understand DeFi, the trade-offs of each, and when a fractional operator beats all of them.","Field guide","STRATEGY",9,
  "DeFi PR agency","DeFi-literate agency criteria, generalist risk, fractional alternative, conflict disclosure.",
  [PB("best-web3-pr-agencies-2026"),"defi-protocol-pr-strategy-2026",PB("fractional-vs-agency"),SVC["web3"]]),
 ("depin-pr-strategy-2026","PR Strategy for a DePIN Project in 2026",
  "DePIN had to become a beat before it could become a story. How to make decentralized-infrastructure coverage land, with the Fluence playbook.","Strategy","STRATEGY",10,
  "DePIN project PR and communications","Category-creation for DePIN, the acronym problem, Fluence/Tom Trowbridge worked example.",
  [SVC["web3"],"/work/fluence",SVC["founder"],PB("tier-1-pr-trap")]),
 ("blockchain-gaming-pr-2026","Blockchain Gaming PR in 2026: How to Promote a Web3 Game",
  "Web3 games have two audiences who hate each other's language. How to run dual-track PR for gamers and crypto media without alienating either.","Strategy","STRATEGY",9,
  "Blockchain PR","Dual-audience gaming PR, gaming press vs crypto press, the Bullieverse India launch lesson.",
  [SVC["web3"],"/work/bullieverse",SVC["kol"],SVC["apac"]]),
 ("web3-infrastructure-pr-2026","PR for a Web3 Infrastructure Startup in 2026",
  "Infra has no token hype and no consumer story. How to make wallets, RPCs, oracles and middleware newsworthy, with the Web3Auth playbook.","Strategy","STRATEGY",9,
  "Web3 PR agency","Infra PR (borrowed credibility, partner brands, developer proof), the Web3Auth Google Cloud lesson.",
  [SVC["web3"],"/work/web3auth",PB("tier-1-pr-trap"),"depin-pr-strategy-2026"]),
 ("crypto-exchange-pr-2026","PR for a Crypto Exchange in 2026",
  "Exchanges live and die on trust. How to run comms across listings, security, regulation and regional access without one breach erasing it all.","Strategy","STRATEGY",9,
  "Crypto PR","Exchange comms (trust, security, listings, regulation), crisis readiness, regional access.",
  [SVC["tge"],"crypto-crisis-communications-2026",SVC["apac"],"exchange-listing-pr-best-practices-2026"]),
 ("rwa-tokenization-pr-2026","PR for an RWA and Tokenization Project in 2026",
  "Real-world assets is where TradFi credibility meets crypto distribution. How to earn coverage that institutions and crypto media both take seriously.","Strategy","STRATEGY",9,
  "Crypto PR","RWA narrative (institutional credibility + crypto reach), the MANTRA $11M Middle East lesson.",
  [SVC["web3"],"/work/mantra-chain",PB("crypto-pr-vs-ai-pr"),"stablecoin-launch-pr-2026"]),
 ("restaking-pr-2026","PR for a Restaking and Intents Project in 2026",
  "The hardest narratives in crypto are the most technical. How to make restaking, intents and shared security legible to editors and AI engines.","Strategy","STRATEGY",9,
  "Web3 PR","Explaining hyper-technical primitives, analogy discipline, category education, AI-citation angle.",
  [SVC["web3"],"depin-pr-strategy-2026",SVC["founder"],GL["geo"]]),
 ("crypto-crisis-communications-2026","Crypto Crisis Communications in 2026: Exploits, Hacks and Depegs",
  "The first hour decides the story. A field guide to running comms through an exploit, hack or depeg, with the holding-statement template.","Pitfalls","CRISIS",10,
  "Security PR","Crisis comms first-hour playbook, holding statements, do/don't list, rebuilding trust after.",
  [SVC["web3"],"crypto-exchange-pr-2026",SVC["cyber"],PB("web3-pr-agency-mistakes")]),
 ("ai-x-crypto-agent-pr-2026","PR for AI x Crypto and Agentic Projects in 2026",
  "Projects at the AI-and-crypto seam need both playbooks at once. How to run credibility-led AI PR and speed-led crypto PR in parallel.","AI","STRATEGY",9,
  "AI startup PR","The intersection play, running two playbooks together, the Gaia AI agents narrative.",
  [PB("crypto-pr-vs-ai-pr"),"/work/gaia-ai",SVC["ai"],SVC["web3"]]),

 # ---- Cluster 4: Web3 PR by region ----
 ("best-web3-pr-agency-india-2026","Best Web3 PR Agencies in India in 2026",
  "India is a home market, not an afterthought. The outlets that matter (Inc42, YourStory, ET), the agencies that get it, and the fractional alternative.","Regional","REGIONAL",9,
  "Web3 PR agency India","Indian Web3 media map, dual-track home-market launch, the Bullieverse lesson.",
  [SVC["apac"],"/india","/work/bullieverse",PB("best-web3-pr-agencies-2026")]),
 ("best-web3-pr-agency-usa-2026","Best Web3 PR Agencies in the USA in 2026",
  "The US crypto press is the most crowded room in the world. How to choose a US-focused agency and what separates access from noise.","Field guide","REGIONAL",9,
  "Web3 PR agency","US outlet landscape, agency selection criteria, fractional vs agency for US founders.",
  [PB("best-web3-pr-agencies-2026"),SVC["web3"],PB("fractional-vs-agency"),PB("get-featured-coindesk-2026")]),
 ("best-crypto-pr-agency-singapore-2026","Best Crypto PR Agencies in Singapore in 2026",
  "Singapore is APAC's crypto capital and a Token2049 anchor. The outlets, the event-led access, and how to choose an agency that has both.","Regional","APAC",9,
  "Crypto PR","Singapore/SEA media map, Token2049 event leverage, regional access criteria.",
  [SVC["apac"],"/singapore",PB("apac-pr-playbook-2026"),"crypto-pr-vietnam-2026"]),
 ("crypto-pr-korea-2026","Crypto PR in Korea in 2026: Outlets, KOLs and Access",
  "Korea is roughly half of Asia's crypto media traffic. The native outlets, the KOL culture, and the compliance shifts you cannot ignore.","Regional","APAC",10,
  "Crypto PR","Korea deep dive (BloomingBit, TokenPost, Coinness), KOL culture, FSC compliance shifts.",
  [SVC["apac"],"/korea",PB("apac-pr-playbook-2026"),"crypto-kol-marketing-korea-2026"]),
 ("crypto-pr-japan-2026","Crypto PR in Japan in 2026: Outlets and Approach",
  "Japan rewards patience, precision and process. The native outlets, the regulatory migration, and why Western pitch habits fail here.","Regional","APAC",9,
  "Crypto PR","Japan deep dive (CryptoTimes JP, Coinpost, Iolite), PSA-to-FIEA migration, cultural pitch norms.",
  [SVC["apac"],"/japan",PB("apac-pr-playbook-2026"),"crypto-pr-korea-2026"]),
 ("crypto-pr-dubai-mena-2026","Crypto PR in Dubai and MENA in 2026",
  "MENA pairs real capital with friendly regulation. How to use Token2049 Dubai, VARA clarity and regional outlets to build a credible story.","Regional","REGIONAL",9,
  "Crypto PR","Dubai/MENA media map, VARA regulatory angle, Token2049 Dubai leverage, the MANTRA lesson.",
  [SVC["apac"],"/dubai-mena","/work/mantra-chain","rwa-tokenization-pr-2026"]),
 ("crypto-pr-vietnam-2026","Crypto PR in Vietnam in 2026",
  "Vietnam is one of the highest crypto-adoption markets on earth and one of the least understood by Western agencies. The outlets and the access.","Regional","APAC",8,
  "Crypto PR","Vietnam media/community map, adoption-led narrative, SEA coordination.",
  [SVC["apac"],PB("apac-pr-playbook-2026"),"best-crypto-pr-agency-singapore-2026",SVC["kol"]]),
 ("token-launch-marketing-agency-india-2026","Token Launch Marketing Agencies in India in 2026",
  "Launching a token with an Indian home base or audience. The agencies, the compliance reality, and the dual-track launch that works here.","Regional","LAUNCH",8,
  "Token launch PR agency","India TGE marketing, compliance/tax reality, dual-track domestic + crypto-native launch.",
  [SVC["tge"],"/india","best-web3-pr-agency-india-2026",PB("pre-token-launch-pr-checklist")]),
 ("ai-startup-pr-agency-india-2026","Best AI Startup PR Agencies in India in 2026",
  "India's AI startup scene is global-facing from day one. How to run PR that earns both Indian and international tech coverage.","Regional","AI",8,
  "AI startup PR agency India","India AI media map, global-from-day-one positioning, agency vs fractional.",
  [SVC["ai"],"/india",PB("ai-startup-pr-2026"),"b2b-saas-pr-agency-2026"]),
 ("apac-press-windows-2026","The Three APAC Press Windows: Timing Crypto News for Asia in 2026",
  "Asia does not read your news when you publish it. The three regional press windows, the translation lag, and how to time a launch across them.","APAC","APAC",9,
  "Crypto PR","Timezone/translation windows, coordinating simultaneous APAC pickup, the RARI translation lesson.",
  [SVC["apac"],PB("apac-pr-playbook-2026"),"/work/rari-chain","crypto-pr-korea-2026"]),

 # ---- Cluster 5: AI startup PR ----
 ("ai-product-launch-pr-2026","PR Strategy for an AI Product Launch in 2026",
  "AI launches drown in their own category noise. How to earn coverage by leading with a concrete use case, not 'AI-native autonomous agents'.","AI","AI",10,
  "AI PR","Use-case-first launch narrative, avoiding buzzword soup, journalist mapping, the demo-proof bar.",
  [SVC["ai"],PB("ai-startup-pr-2026"),"/work/gaia-ai","ai-thought-leadership-pr-2026"]),
 ("ai-series-a-funding-announcement-pr-2026","AI Startup Series A Funding Announcement PR in 2026",
  "A raise is a commodity until you frame it. How to turn an AI Series A into a category story instead of another funding-round line item.","AI","AI",9,
  "AI startup PR","Funding-as-category-story, investor angle, the dual-asset raise-plus-profile play.",
  [SVC["ai"],PB("ai-startup-pr-2026"),"/work/mantra-chain",PB("op-eds-vs-press-releases")]),
 ("ai-thought-leadership-pr-2026","AI Thought Leadership in 2026: Executive Positioning That Works",
  "In AI, credibility is the whole game. How to position a technical founder as a category authority across op-eds, podcasts and analyst rooms.","Founder","AI",9,
  "Thought leadership","AI executive positioning, op-ed + podcast + analyst cadence, author-entity build for AI search.",
  [SVC["founder"],PB("founder-profiling-sprint"),PB("op-eds-vs-press-releases"),GL["geo"]]),
 ("enterprise-ai-pr-2026","PR for an Enterprise AI Company in 2026",
  "Enterprise buyers trust analysts and peers, not hype. How to run AI PR that lands in the rooms a CIO actually reads, including analyst relations.","AI","AI",9,
  "AI PR","Enterprise AI PR (analyst relations, customer proof, trade press), the B2B credibility ladder.",
  [SVC["ai"],"b2b-saas-pr-agency-2026",SVC["cyber"],PB("ai-startup-pr-2026")]),
 ("healthcare-ai-pr-2026","PR for a Healthcare AI Startup in 2026",
  "Healthcare AI carries a trust and regulatory burden no consumer app does. How to run comms that respects evidence, the FDA and skeptical reporters.","AI","AI",9,
  "AI startup PR agency","Healthcare AI PR (evidence-led, regulatory-aware, clinical proof), the credibility-first narrative.",
  [SVC["ai"],"enterprise-ai-pr-2026",PB("ai-startup-pr-2026"),PB("crypto-pr-vs-ai-pr")]),
 ("what-is-an-ai-publicist-2026","What an AI Publicist Actually Does in 2026",
  "Half buzzword, half real role. What an AI publicist is, what they should deliver, and how to tell a specialist from a rebadged generalist.","AI","AI",8,
  "Crypto publicist","Defining the AI publicist role, deliverables, specialist vs generalist test, fractional model.",
  [SVC["ai"],GL["frac"],PB("ai-startup-pr-2026"),"crypto-publicist-vs-agency-2026"]),
 ("how-to-get-ai-startup-in-techcrunch-2026","How to Get Your AI Startup Into TechCrunch in 2026",
  "TechCrunch still sets the startup agenda. What its reporters cover, the exclusive-vs-embargo call, and a pitch that does not get deleted.","AI","TIER-1",9,
  "How to get op-ed published in TechCrunch","TechCrunch newsroom map, exclusive mechanics, pitch template, what gets ignored.",
  [SVC["ai"],PB("ai-startup-pr-2026"),"how-to-submit-op-ed-techcrunch-2026",PB("get-featured-coindesk-2026")]),
 ("how-to-get-covered-the-information-2026","How to Get Covered by The Information in 2026",
  "The Information is the hardest, highest-credibility tech room. What clears its bar, why scoops and sourcing rule, and when to even try.","AI","TIER-1",8,
  "AI PR","The Information's standards, scoop culture, the named-source bar, realistic expectations.",
  [SVC["ai"],"how-to-get-ai-startup-in-techcrunch-2026",PB("tier-1-pr-trap"),PB("ai-startup-pr-2026")]),
 ("ai-pr-agency-pricing-packages-2026","AI PR Agency Pricing and Packages in 2026",
  "What AI PR actually costs across agency, fractional and project models, what each tier buys, and the line items founders miss.","Pricing","PRICING",9,
  "AI PR","AI-PR-specific pricing, agency vs fractional vs project, analyst-relations cost, ROI framing.",
  [PB("crypto-pr-cost-2026"),SVC["ai"],PB("fractional-vs-agency"),PB("ai-startup-pr-2026")]),
 ("best-b2b-saas-pr-agencies-2026","Best B2B SaaS PR Agencies Ranked in 2026",
  "B2B SaaS PR is a different sport from consumer. A criteria-led look at the field, what separates the best, and the fractional alternative.","Field guide","STRATEGY",9,
  "Best Web3 PR agencies 2025","B2B SaaS PR criteria, category vs product PR, agency vs fractional, named trade-offs.",
  [PB("best-web3-pr-agencies-2026"),SVC["ai"],"enterprise-ai-pr-2026",PB("fractional-vs-agency")]),

 # ---- Cluster 6: founder profiling / thought leadership ----
 ("how-to-build-founder-thought-leadership-2026","How to Build Founder Thought Leadership in 2026",
  "Thought leadership is earned, not posted. The cadence, the channels and the author-entity build that turns a founder into a cited authority.","Founder","FOUNDER",10,
  "Thought leadership","The full thought-leadership system, op-ed + social + speaking + entity build, AI-citation payoff.",
  [SVC["founder"],PB("founder-profiling-sprint"),PB("op-eds-vs-press-releases"),GL["geo"]]),
 ("personal-brand-crypto-founder-2026","How to Build a Personal Brand as a Crypto Founder in 2026",
  "The Twitter-and-LinkedIn playbook for crypto founders who would rather ship. What to post, what to never post, and how to sound like yourself.","Founder","FOUNDER",9,
  "Personal brand crypto founder","Crypto founder personal brand, X/LinkedIn cadence, authenticity vs performance, the humaniser lesson.",
  [SVC["founder"],PB("founder-profiling-sprint"),"personal-brand-startup-founder-2026","linkedin-strategy-founders-2026"]),
 ("personal-brand-startup-founder-2026","How to Build a Personal Brand as a Startup Founder in 2026",
  "For AI and tech founders. The content cadence, the platform choices, and the line between useful authority and LinkedIn cringe.","Founder","FOUNDER",9,
  "How to build personal brand as startup founder","Founder personal brand for tech/AI, platform strategy, content pillars, consistency over virality.",
  [SVC["founder"],PB("founder-profiling-sprint"),"personal-brand-crypto-founder-2026","ai-thought-leadership-pr-2026"]),
 ("how-to-get-podcast-interviews-founder-2026","How to Get Podcast Interviews as a Founder in 2026",
  "Podcasts are the most underrated founder channel. How to build a target list, pitch hosts, and turn one tour into a quarter of authority.","Founder","FOUNDER",8,
  "How to build personal brand as startup founder","Podcast target-list building, host pitching, the Gaia AI 6-podcast tour lesson, repurposing.",
  [SVC["founder"],"/work/gaia-ai",PB("founder-profiling-sprint"),"how-to-build-founder-thought-leadership-2026"]),
 ("how-to-submit-op-ed-techcrunch-2026","How to Submit an Op-Ed to TechCrunch (and Where Else) in 2026",
  "TechCrunch rarely runs outside op-eds, so where do founder essays actually land? The real opinion-desk map and a submission that works.","Founder","CONTENT",8,
  "How to get op-ed published in TechCrunch","Op-ed submission reality, the real opinion-desk map, what editors accept, ghostwriting note.",
  [SVC["content"],PB("op-eds-vs-press-releases"),"op-ed-ghostwriting-executives-2026","how-to-get-ai-startup-in-techcrunch-2026"]),
 ("op-ed-ghostwriting-executives-2026","Op-Ed Ghostwriting for Executives in 2026: How It Works",
  "The founder's name, the founder's thinking, an editor-ready piece. What ghostwriting actually involves, what it costs, and how to keep it authentic.","Content","CONTENT",8,
  "Thought leadership","Ghostwriting process, voice capture, the authenticity bar, pricing, placement.",
  [SVC["content"],PB("op-eds-vs-press-releases"),SVC["founder"],"how-to-submit-op-ed-techcrunch-2026"]),
 ("how-to-get-speaking-slots-crypto-conferences-2026","How to Get Speaking Slots at Crypto Conferences in 2026",
  "Consensus, Token2049, ETHDenver and the rest. How conference programming actually works and how founders earn a real slot, not a side stage.","Founder","FOUNDER",9,
  "How to get Bloomberg crypto coverage","Conference programming reality, how slots are chosen, the pitch, event-led PR leverage.",
  [SVC["founder"],PB("apac-pr-playbook-2026"),"how-to-build-founder-thought-leadership-2026",SVC["apac"]]),
 ("best-founder-personal-branding-agencies-2026","Best Founder Personal Branding Agencies in 2026",
  "A criteria-led look at the founder-branding field, what separates real positioning from ghostwritten LinkedIn spam, and the fractional model.","Field guide","FOUNDER",9,
  "Founder personal branding","Founder-branding agency criteria, positioning vs content-mill, conflict disclosure, fractional alternative.",
  [SVC["founder"],PB("founder-profiling-sprint"),PB("best-web3-pr-agencies-2026"),"personal-brand-startup-founder-2026"]),
 ("linkedin-strategy-founders-2026","LinkedIn Strategy for Web3 and AI Founders in 2026",
  "LinkedIn's 2026 algorithm rewards substance and consistency. The posting system that builds authority without turning into a motivational account.","Founder","FOUNDER",8,
  "Personal brand crypto founder","LinkedIn content system, the 2026 algorithm, pillars, cadence, voice, what flops.",
  [SVC["founder"],"personal-brand-startup-founder-2026",PB("founder-profiling-sprint"),"how-to-build-founder-thought-leadership-2026"]),
 ("how-to-get-into-forbes-councils-2026","How to Get Into a Forbes Council in 2026 (and Whether You Should)",
  "Forbes Councils are pay-to-publish, and that changes what they are worth. The honest cost-benefit, the credibility trap, and the alternatives.","Founder","CONTENT",8,
  "How to get featured in crypto media","Forbes Councils decoded, pay-to-play reality, when it helps, earned alternatives.",
  [PB("op-eds-vs-press-releases"),"how-to-get-crypto-project-into-forbes-2026",SVC["founder"],SVC["content"]]),

 # ---- Cluster 7: fractional PR ----
 ("best-fractional-pr-consultant-tech-2026","Best Fractional PR Consultants for Tech Startups in 2026",
  "What a fractional PR consultant is, how to evaluate one, and why a senior operator part-time often beats a junior-staffed agency full-time.","Operations","OPERATIONS",9,
  "Best fractional PR consultant tech","Fractional consultant evaluation, seniority test, fractional vs agency for tech founders.",
  [GL["frac"],PB("fractional-vs-agency"),SVC["web3"],"fractional-pr-cost-pricing-2026"]),
 ("best-fractional-pr-consultant-web3-2026","Best Fractional PR Consultant for a Web3 Startup in 2026",
  "Web3 moves too fast for agency layers. Why fractional fits crypto founders, what to look for, and the trade-offs to weigh honestly.","Operations","OPERATIONS",9,
  "PR consultant","Fractional for Web3 specifically, speed/access argument, what a good one delivers.",
  [GL["frac"],PB("fractional-vs-agency"),"best-fractional-pr-consultant-tech-2026",SVC["web3"]]),
 ("fractional-pr-cost-pricing-2026","Fractional PR Cost and Monthly Retainer Pricing in 2026",
  "What fractional PR really costs, what a retainer should include, and how to tell a fair price from an underqualified one.","Pricing","PRICING",8,
  "Fractional PR","Fractional pricing detail, retainer scope, fair-price test, vs agency cost.",
  [PB("crypto-pr-cost-2026"),GL["frac"],PB("fractional-vs-agency"),"best-fractional-pr-consultant-tech-2026"]),
 ("fractional-cmo-web3-2026","Fractional CMO for a Web3 Startup in 2026: When It Makes Sense",
  "A fractional CMO owns the whole growth function, not just PR. When a Web3 startup needs one, when it needs fractional PR instead, and the overlap.","Operations","OPERATIONS",8,
  "Fractional PR for Web3 startup","Fractional CMO vs fractional PR, scope, stage-fit, when each is right.",
  [GL["frac"],PB("fractional-vs-agency"),"best-fractional-pr-consultant-web3-2026",SVC["web3"]]),
 ("fractional-pr-vs-in-house-hire-2026","Fractional PR vs Hiring an In-House PR Lead in 2026",
  "The build-vs-rent decision for comms. Cost, speed, seniority and risk compared, with a decision tree for founders at each stage.","Operations","OPERATIONS",8,
  "Fractional PR","Fractional vs in-house hire, total cost, ramp time, seniority, stage-based decision tree.",
  [GL["frac"],PB("fractional-vs-agency"),"fractional-pr-cost-pricing-2026","when-to-hire-fractional-pr-2026"]),
 ("when-to-hire-fractional-pr-2026","When Should a Startup Hire Fractional PR in 2026?",
  "Too early wastes money; too late wastes momentum. The signals that say it is time, and the milestones that should trigger a comms hire.","Operations","OPERATIONS",7,
  "Fractional PR","Timing signals for hiring PR, pre-launch vs post-raise, what to do before you can afford it.",
  [GL["frac"],PB("fractional-vs-agency"),"fractional-pr-vs-in-house-hire-2026",SVC["web3"]]),

 # ---- Cluster 8: KOL / influencer ----
 ("best-crypto-kol-marketing-agencies-2026","Best Crypto KOL Marketing Agencies in 2026",
  "A criteria-led look at KOL agencies, the fraud problem nobody audits, and how to choose one that vets creators before it bills you.","Field guide","KOL",9,
  "Best crypto PR agency globally","KOL agency criteria, fraud/bot audit, regional coverage, conflict disclosure, fractional network.",
  [SVC["kol"],"how-to-vet-crypto-kols-2026",PB("best-web3-pr-agencies-2026"),"crypto-influencer-pricing-rates-2026"]),
 ("kol-campaign-token-launch-2026","How to Run a KOL Campaign for a Token Launch in 2026",
  "The three-wave KOL sequence that actually moves a launch: credibility anchors, broad activation, sustained deep-dives, with timing and briefs.","KOL","KOL",9,
  "Web3 token launch strategy","Three-wave KOL model, T-72h/T+0/T+24h timing, briefs, disclosure, attribution.",
  [SVC["kol"],PB("pre-token-launch-pr-checklist"),SVC["tge"],"how-to-vet-crypto-kols-2026"]),
 ("crypto-influencer-pricing-rates-2026","Crypto Influencer and KOL Pricing: 2026 Rates",
  "What KOLs actually charge in 2026 by tier and platform, the all-in budget multiplier, and where creator spend quietly leaks.","Pricing","KOL",8,
  "Top crypto PR 2025","2026 KOL rate card (nano to macro), platform differences, all-in budget, regional premiums.",
  [SVC["kol"],"best-crypto-kol-marketing-agencies-2026",PB("crypto-pr-cost-2026"),"kol-campaign-token-launch-2026"]),
 ("crypto-kol-marketing-korea-2026","Crypto KOL Marketing in Korea in 2026",
  "Korea's KOL scene runs by its own rules, rates and platforms. How to activate Korean creators credibly without importing Western playbooks.","Regional","KOL",8,
  "Best crypto PR agency globally","Korea KOL culture, platforms, rate premiums, disclosure norms, native-brief discipline.",
  [SVC["kol"],"/korea","crypto-pr-korea-2026",SVC["apac"]]),
 ("how-to-vet-crypto-kols-2026","How to Vet Crypto KOLs in 2026 (and Spot Fake Engagement)",
  "Most KOL spend is wasted on bought audiences. The independent-audit checklist that catches bots, fake reach and dead engagement before you sign.","KOL","KOL",9,
  "Crypto PR agency comparison","KOL vetting checklist, bot/engagement audit, on-chain track record, red flags.",
  [SVC["kol"],"best-crypto-kol-marketing-agencies-2026","crypto-influencer-pricing-rates-2026",PB("web3-pr-agency-mistakes")]),
 ("web3-kol-agency-vs-in-house-2026","Web3 KOL Agency vs Building Your Own Creator List in 2026",
  "Rent the network or build it. The cost, control and risk trade-offs of a KOL agency versus an in-house creator program.","KOL","KOL",8,
  "Web3 agency","Agency vs in-house KOL, cost/control/risk, when each wins, hybrid model.",
  [SVC["kol"],"best-crypto-kol-marketing-agencies-2026",PB("fractional-vs-agency"),"how-to-vet-crypto-kols-2026"]),
 ("top-crypto-marketing-agencies-2026","Top Crypto Marketing Agencies in 2026: How to Compare Them",
  "Marketing, PR, KOL and growth get lumped together and shouldn't be. A map of the field and how to choose by what you actually need.","Field guide","STRATEGY",9,
  "Top crypto PR 2025","Crypto marketing landscape map, PR vs growth vs KOL, selection criteria, fractional option.",
  [PB("best-web3-pr-agencies-2026"),"web3-marketing-agency-guide-2026",SVC["web3"],SVC["kol"]]),
 ("web3-marketing-agency-guide-2026","How to Choose a Web3 Marketing Agency in 2026",
  "A buyer's guide to picking a Web3 marketing partner: the questions that expose depth, the red flags, and how to match model to stage.","Strategy","STRATEGY",9,
  "Web3 marketing PR agency","Web3 agency buyer's guide, vetting questions, red flags, model-to-stage matching.",
  [PB("best-web3-pr-agencies-2026"),"top-crypto-marketing-agencies-2026",PB("web3-pr-agency-mistakes"),PB("fractional-vs-agency")]),

 # ---- Cluster 9: cybersecurity PR ----
 ("cybersecurity-pr-agency-pricing-2026","Cybersecurity PR Agency Retainer Pricing in 2026",
  "What cybersecurity PR costs, why analyst relations changes the math, and how a fractional model compares to a median Series B retainer.","Pricing","CYBER",8,
  "Cybersecurity PR agency","Cyber PR pricing, analyst-relations cost, fractional vs agency, the ~$23.5K median benchmark.",
  [SVC["cyber"],PB("cybersecurity-pr-2026"),PB("crypto-pr-cost-2026"),PB("fractional-vs-agency")]),
 ("how-to-get-covered-dark-reading-2026","How to Get Covered by Dark Reading in 2026",
  "Dark Reading rewards research, not pitches. What its editors run, why threat findings beat product news, and a pitch that respects the desk.","Cyber","CYBER",9,
  "Cybersecurity PR","Dark Reading newsroom map, research-led pitching, what gets ignored, the threat-research angle.",
  [SVC["cyber"],PB("cybersecurity-pr-2026"),"cybersecurity-threat-research-pr-2026","how-to-get-featured-in-decrypt-2026"]),
 ("cybersecurity-analyst-relations-2026","Cybersecurity Analyst Relations in 2026: Gartner, Forrester and IDC",
  "Analysts shape the shortlist before press ever runs. The briefing cadence, the Magic Quadrant and Wave reality, and how vendors earn inclusion.","Cyber","CYBER",10,
  "Cybersecurity communications","Analyst-relations program, briefing cadence, MQ/Wave inclusion mechanics, AR vs PR.",
  [SVC["cyber"],PB("cybersecurity-pr-2026"),"enterprise-ai-pr-2026","cybersecurity-pr-agency-pricing-2026"]),
 ("cybersecurity-threat-research-pr-2026","Turning Threat Research Into Coverage in 2026",
  "A good vulnerability report is the best PR a security vendor has. How to package research for coverage without crossing disclosure lines.","Cyber","CYBER",9,
  "Cybersecurity PR","Threat-research-led PR, packaging findings, coordinated disclosure, named security desks.",
  [SVC["cyber"],"how-to-get-covered-dark-reading-2026",PB("cybersecurity-pr-2026"),"cybersecurity-breach-crisis-comms-2026"]),
 ("cybersecurity-breach-crisis-comms-2026","Cybersecurity Breach and Crisis Communications in 2026",
  "When you are the breach, not the researcher. The first-hour playbook, the holding statement, and how to communicate through an incident.","Cyber","CRISIS",9,
  "Security PR","Breach comms playbook, holding statements, regulatory notification, trust rebuild.",
  [SVC["cyber"],"crypto-crisis-communications-2026",PB("cybersecurity-pr-2026"),"cybersecurity-threat-research-pr-2026"]),
 ("best-cybersecurity-marketing-agencies-2026","Best Marketing Agencies for Cybersecurity Firms in 2026",
  "Cybersecurity marketing is a credibility game most agencies misread. A criteria-led field guide and the analyst-aware alternative.","Field guide","CYBER",9,
  "Security PR","Cyber marketing agency criteria, analyst literacy, generalist risk, fractional alternative.",
  [SVC["cyber"],PB("cybersecurity-pr-2026"),"cybersecurity-analyst-relations-2026",PB("best-web3-pr-agencies-2026")]),

 # ---- Cluster 10: GEO / AEO / measurement / strategy ----
 ("how-to-build-ai-search-visibility-geo-2026","How to Build AI Search Visibility (GEO) for a Startup in 2026",
  "When buyers ask ChatGPT instead of Google, getting cited is the win. The earned-media and content moves that make AI engines name your brand.","AI Search","AI SEARCH",10,
  "AI startup PR","GEO program for startups, earned-media + entity + content, what gets cited, measurement.",
  [GL["geo"],PB("op-eds-vs-press-releases"),"how-to-get-cited-by-chatgpt-2026","aeo-vs-seo-startups-2026"]),
 ("how-to-get-cited-by-chatgpt-2026","How to Get Your Brand Cited by ChatGPT and Perplexity in 2026",
  "Citations come from trust signals AI engines can extract. The concrete tactics that turn earned coverage into answer-engine mentions.","AI Search","AI SEARCH",9,
  "AI startup PR","ChatGPT/Perplexity citation tactics, source trust, structured content, named-entity consistency.",
  [GL["geo"],"how-to-build-ai-search-visibility-geo-2026",PB("op-eds-vs-press-releases"),SVC["content"]]),
 ("aeo-vs-seo-startups-2026","AEO vs SEO: What Startups Actually Need in 2026",
  "Answer-engine optimization is not a replacement for SEO, it's a layer on top. What's different, what overlaps, and where to spend first.","AI Search","AI SEARCH",8,
  "AI startup PR","AEO vs SEO vs GEO clarified, Google's 'still SEO' position, priority order for startups.",
  [GL["geo"],"how-to-build-ai-search-visibility-geo-2026","how-to-get-cited-by-chatgpt-2026",SVC["content"]]),
 ("how-to-measure-pr-roi-2026","How to Measure PR ROI and Share of Voice in 2026",
  "Impressions are vanity. The metrics that actually map PR to pipeline, the share-of-voice method, and what to report to a board.","Strategy","STRATEGY",9,
  "Top crypto PR 2025","PR ROI framework, SOV measurement, vanity vs real metrics, board reporting.",
  [SVC["web3"],"share-of-voice-crypto-2026",PB("crypto-pr-cost-2026"),GL["geo"]]),
 ("share-of-voice-crypto-2026","Share of Voice in Crypto: How to Track It in 2026",
  "Share of voice is the one metric that survives a bear market. How to define your set, measure it, and use it to steer a comms program.","Strategy","STRATEGY",8,
  "Top crypto PR 2025","SOV definition, competitor set, measurement method, using SOV to allocate effort.",
  [SVC["web3"],"how-to-measure-pr-roi-2026",PB("crypto-pr-vs-ai-pr"),SVC["kol"]]),
 ("how-to-choose-web3-pr-agency-checklist-2026","How to Choose a Web3 PR Agency in 2026: The Checklist",
  "A founder-ready checklist for evaluating Web3 PR agencies: the questions that expose real access, the red flags, and the model-fit test.","Field guide","STRATEGY",9,
  "Web3 PR agency","Agency-selection checklist, access-vs-noise test, red flags, conflict and reporting questions.",
  [PB("best-web3-pr-agencies-2026"),PB("web3-pr-agency-mistakes"),PB("fractional-vs-agency"),"web3-pr-agency-reviews-clutch-2026"]),
 ("web3-pr-agency-reviews-clutch-2026","Web3 PR Agency Reviews on Clutch in 2026: How to Read Them",
  "Review sites are gameable. How to read Clutch, G2 and Trustpilot ratings for PR agencies without being misled by curated testimonials.","Field guide","STRATEGY",7,
  "Web3 PR agency reviews","Reading review sites critically, what ratings hide, reference-check questions.",
  [PB("best-web3-pr-agencies-2026"),"how-to-choose-web3-pr-agency-checklist-2026",PB("fractional-vs-agency"),SVC["web3"]]),
 ("pr-for-tech-startups-guide-2026","PR for Tech Startups in 2026: A Founder's Guide",
  "The whole PR picture for an early tech startup: when to start, what to spend, what to do yourself, and what actually earns coverage.","Strategy","STRATEGY",10,
  "Web3 PR agency for startups","End-to-end startup PR primer, DIY vs hire, budget, news hooks, the credibility ladder.",
  [SVC["web3"],PB("crypto-pr-cost-2026"),"founder-led-diy-pr-2026",PB("tier-1-pr-trap")]),
 ("b2b-tech-pr-guide-2026","B2B Tech PR in 2026: What's Different",
  "B2B PR sells to a buying committee, not a crowd. How category narrative, analyst relations and customer proof replace consumer-style hype.","Strategy","STRATEGY",9,
  "TGE PR","B2B PR fundamentals, buying-committee narrative, analyst relations, customer proof.",
  [SVC["ai"],"enterprise-ai-pr-2026","best-b2b-saas-pr-agencies-2026",PB("crypto-pr-vs-ai-pr")]),
 ("earned-vs-paid-media-web3-2026","Earned vs Paid Media in Web3 in 2026",
  "Paid buys reach; earned builds belief. Where each fits in a Web3 budget, why credibility outlasts impressions, and how to blend them.","Strategy","STRATEGY",8,
  "Web3 marketing PR agency","Earned vs paid trade-offs, credibility compounding, blending, the sponsored-content firewall.",
  [SVC["web3"],PB("op-eds-vs-press-releases"),"crypto-press-release-distribution-2026",SVC["kol"]]),

 # ---- Cluster 11: long-tail comparisons / pricing / mistakes ----
 ("crypto-pr-small-budget-2026","Crypto PR on a Small Budget in 2026: What's Actually Possible",
  "You do not need a $40K sprint to earn coverage. The high-leverage moves a lean team can run themselves, and where to spend the first dollar.","Pricing","PRICING",9,
  "Crypto PR","Lean-budget PR tactics, DIY high-leverage moves, first-dollar priorities, when to upgrade.",
  [PB("crypto-pr-cost-2026"),"affordable-pr-tech-startup-2026","founder-led-diy-pr-2026",SVC["web3"]]),
 ("affordable-pr-tech-startup-2026","Affordable PR for Tech Startups in 2026",
  "What 'affordable PR' really buys, the models that fit a small budget, and how to avoid cheap services that quietly cost you credibility.","Pricing","PRICING",8,
  "Affordable PR for tech startup","Affordable PR models, fractional/project/DIY, cheap-service traps, value test.",
  [GL["frac"],"crypto-pr-small-budget-2026",PB("crypto-pr-cost-2026"),PB("fractional-vs-agency")]),
 ("crypto-publicist-vs-agency-2026","Crypto Publicist vs PR Agency in 2026: Which Do You Need?",
  "A solo publicist gives you senior attention; an agency gives you bench. The honest trade-offs and which fits your stage and budget.","Operations","OPERATIONS",8,
  "Crypto publicist","Publicist vs agency vs fractional, seniority vs bandwidth, stage-fit decision.",
  [GL["frac"],PB("fractional-vs-agency"),"what-is-an-ai-publicist-2026",SVC["web3"]]),
 ("how-to-write-crypto-press-release-2026","How to Write a Crypto Press Release That Gets Picked Up in 2026",
  "Most releases die in the inbox. The structure, the dated news peg, and the compliance lines that make a release pickup-ready.","Content","PRESS",8,
  "Web3 press release","Press-release structure, news peg, boilerplate, compliance, the pitch that accompanies it.",
  [SVC["content"],"crypto-press-release-distribution-2026",PB("op-eds-vs-press-releases"),PB("how-to-pitch-cointelegraph-2026")]),
 ("crypto-pr-agency-comparison-2026","How to Compare Crypto PR Agencies in 2026",
  "A practical framework for comparing crypto PR agencies side by side: access, seniority, model, reporting and price, with a scoring rubric.","Field guide","STRATEGY",8,
  "Crypto PR agency comparison","Comparison framework, scoring rubric, what to weight, fractional in the mix.",
  [PB("best-web3-pr-agencies-2026"),"how-to-choose-web3-pr-agency-checklist-2026",PB("fractional-vs-agency"),"web3-pr-agency-reviews-clutch-2026"]),
 ("web3-pr-bear-market-2026","Web3 PR in a Bear Market in 2026",
  "Bear markets are when share of voice is cheapest to win. How to keep building narrative and credibility when budgets and attention contract.","Strategy","STRATEGY",8,
  "Crypto PR","Bear-market PR strategy, SOV opportunity, credibility building, lean tactics.",
  [SVC["web3"],"share-of-voice-crypto-2026",PB("crypto-pr-cost-2026"),"crypto-pr-small-budget-2026"]),
 ("crypto-newsjacking-2026","Newsjacking for Crypto Brands in 2026",
  "The fastest free coverage is a smart reaction to breaking news. How to newsjack responsibly, where it backfires, and how to move in minutes.","Strategy","STRATEGY",8,
  "How to get media coverage Web3","Newsjacking method, speed and relevance, reputational risk, the reactive-comment pitch.",
  [SVC["web3"],"crypto-media-relations-guide-2026",PB("how-to-pitch-cointelegraph-2026"),"crypto-crisis-communications-2026"]),
 ("founder-led-diy-pr-2026","DIY PR in 2026: How Founders Can Run Their Own Comms",
  "Before you can afford help, you can still earn coverage. The founder-run PR system: news hooks, a media list, pitching and a posting cadence.","Strategy","STRATEGY",9,
  "How to get media coverage Web3","Founder DIY PR system, building a media list, self-pitching, when to hand off.",
  [SVC["web3"],"crypto-pr-small-budget-2026","when-to-hire-fractional-pr-2026",PB("get-featured-coindesk-2026")]),
 ("token-launch-pr-mistakes-2026","The Most Common Token Launch PR Mistakes in 2026",
  "The avoidable errors that quietly sink a TGE: no news hook, hype with no proof, ignoring APAC, KOL fraud, and going silent after launch.","Pitfalls","LAUNCH",9,
  "Token launch PR","TGE-specific mistakes and fixes, the post-launch silence trap, compliance errors.",
  [PB("web3-pr-agency-mistakes"),PB("pre-token-launch-pr-checklist"),SVC["tge"],"post-tge-pr-first-90-days-2026"]),
 ("coindesk-vs-cointelegraph-where-to-pitch-2026","CoinDesk vs Cointelegraph in 2026: Where to Pitch What",
  "Two flagship outlets, two different newsrooms. Which story belongs where, how their desks differ, and how to sequence a pitch across both.","Tier-1","TIER-1",9,
  "Crypto media relations","Head-to-head outlet comparison, desk-by-desk, story-to-outlet matching, sequencing.",
  [PB("get-featured-coindesk-2026"),PB("how-to-pitch-cointelegraph-2026"),"how-to-get-featured-in-decrypt-2026",SVC["web3"]]),
]

def norm_link(l):
    # bare slug -> /playbook/<slug>
    if l.startswith("/"):
        return l
    return f"/playbook/{l}"

assert len(T) == 100, f"expected 100 topics, got {len(T)}"
slugs = [t[0] for t in T]
assert len(set(slugs)) == 100, "duplicate slugs"

EXISTING = {
 "tier-1-pr-trap","apac-pr-playbook-2026","founder-profiling-sprint","crypto-pr-cost-2026",
 "get-featured-coindesk-2026","fractional-vs-agency","best-web3-pr-agencies-2026","crypto-pr-vs-ai-pr",
 "ai-startup-pr-2026","cybersecurity-pr-2026","web3-pr-agency-mistakes","pre-token-launch-pr-checklist",
 "how-to-pitch-cointelegraph-2026","op-eds-vs-press-releases",
}
for s in slugs:
    assert s not in EXISTING, f"slug collides with existing playbook: {s}"

out = []
for i,(slug,title,deck,tag,cat,time,kw,angle,links) in enumerate(T):
    n = START_N + i
    out.append({
        "n": n,
        "slug": slug,
        "title": title,
        "deck": deck,
        "tag": tag,
        "cat": cat,
        "time": time,
        "primaryKeyword": kw,
        "angle": angle,
        "links": [norm_link(l) for l in links],
    })

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
path = os.path.join(root, "data", "playbook-topics.json")
with open(path, "w") as f:
    json.dump(out, f, indent=2, ensure_ascii=False)
print(f"wrote {len(out)} topics -> {path}")
print(f"numbers {out[0]['n']}..{out[-1]['n']}")
